export const meta = {
  name: 'pp-motion-research-concept-v2',
  description: 'Research world-class motion design + assets/tools, 3 competing concepts (with a mandatory real-iPhone site sequence) judged, synthesized into a production bible',
  phases: [
    { title: 'Research', detail: 'craft rules from top studios, repo knowledge + toolkit, sound design' },
    { title: 'Concepts', detail: '3 independent concepts (script + storyboard)' },
    { title: 'Judge', detail: '3 judges score every concept' },
    { title: 'Bible', detail: 'synthesize the winner into BRIEF.md + SCENES.md' },
  ],
}

const ROOT = '/home/user/DevDoctor/ads'
const OUT = ROOT + '/purepeptide-motion-en'
const RULES = `
HARD RULES (compliance, binding for every idea):
- Product: PurePeptide research peptides (purepeptide.care). English, research positioning. Legal line must appear on the end card >= 2.5 s, >= 24 px: "For laboratory research use only · Not for human or veterinary consumption · 21+".
- NEVER show or mention: people, hands, fingers, faces, body parts, syringes, needles, pills, injections, doctors, dosages, protocols, effects or benefits (no health, recovery, muscle, weight, anti-aging, results, benefits, heal, treatment, dose, cycle). No invented numbers, certifications, reviews, awards, competitor names.
- Only these claims (all from the site): every batch independently tested (lab named on site: Janoshik Analytical — text only, no logo); identity confirmed; purity measured by HPLC, 99% minimum; shipped cold within 24 hours; ships to 10 countries; six compounds in the catalog (BPC-157/TB-500, CJC-1295/IPA, GHK-Cu, IGF-1 LR3, Selank, Semax — names only as printed on labels); offers: 2 vials −5%, 3+ vials −8%, free shipping over $200, applied automatically in the cart. Tagline: "Purity, proven." URL purepeptide.care. Do NOT say certificates are published online (the /coa/ page still says coming soon). The live site also lists a "Retatrutide" product: it must never be visible or named in the ad.
- Text >= 24 px, contrast >= 4.5:1, inside title-safe (x 96–1824, y 54–1026).
MANDATORY SEQUENCE (client request): "a real iPhone that goes on the PurePeptide site". A photoreal iPhone (modelled in Blender after the latest iPhone Pro: flat aluminium sides, Dynamic Island, full-width camera plateau, NO Apple logo) shown in 3D, navigating the REAL purepeptide.care mobile site (genuine screenshots captured at iPhone viewport 393x852 @3x, to be found in ${OUT}/assets/site/, index ${OUT}/assets/site/SITE.md): e.g. home hero -> shop / product page -> add to cart -> cart where the bundle discount appears automatically -> checkout-ready. Taps are shown only by subtle touch rings on the glass (no finger, no hand). Budget 9–14 s of the 45 s, best placed where it carries the offers and the CTA. Production contract for the phone (being built now in parallel, in ${OUT}/assets/iphone/): a Blender 3D fly-in/turn shot (RGBA PNG sequence, 1920x1080, ~3 s, ending exactly on the frontal pose), a frontal pose split into body layer (screen transparent) + glass-reflection layer + screen_rect.json (pixel rect + corner radius) so HyperFrames animates the live site inside the screen (scroll, page push, cart update) with the phone group free to move/scale in 2D; optionally a short tilt-away 3D shot. The screen content is crisp HTML/PNG compositing, not baked.
BUDGET: the client asked to spend very few ElevenLabs credits. Plan exactly ONE ElevenLabs v4 voice-over take (voice "Markmont", proven warm/deep/confident, emotion tags), NO new AI video generations (reuse the existing photoreal real-vial clips), music reused from an existing project file (purepeptide-*/assets/audio/music_raw.mp3 — pick the best fit, re-edited/looped in Python) or at most ONE new ElevenLabs music generation if nothing fits, all SFX synthesized locally (python audiolib.py) or reused from existing project files.
Deliverable: 45.0 s motion design ad, 1920x1080, 30 fps, English voice-over, built in HyperFrames (HTML + GSAP, one paused deterministic timeline) with SVG/CSS/canvas, pre-rendered WebGL or Blender plates and the AI vial clips where they serve the idea. The machine has only 4 CPUs (headless Chromium + SwiftShader, Blender CPU): prefer techniques that stay premium yet render fast.`

phase('Research')
const research = await parallel([
  () => agent(`You are a motion-design researcher. Use WebSearch/WebFetch widely (at least 15 distinct sources: studio sites, case studies, Motionographer, Behance/Vimeo write-ups, School of Motion, Awwwards, talks/interviews). Study the work regarded as the best motion design of the last years: BUCK, ManvsMachine, Ordinary Folk, Gunner, Oddfellows, Giant Ant, Tendril, Apple product launch motion (iPhone feature films and how Apple shows apps/websites on iPhone: device choreography, screen push-ins, UI close-ups, depth of field on device), Stripe Sessions, Linear and Vercel launch films, Spotify Wrapped, Nike/Apple kinetic type spots, award winners (Motion Awards, Vimeo Staff Picks, Annecy commissioned films), and premium "app/website on phone" e-commerce ads.
Extract CONCRETE, MEASURABLE craft rules a code-based animator can apply: easing curves (cubic-bezier values / named eases, overshoot amounts), typical durations per move in frames at 30 fps, hold times, how many elements move at once, transition taxonomy (match cut, morph, mask wipe, zoom-through, object-led transition, whip, liquid), how type is animated (tracking, per-letter stagger values, masks, variable fonts), colour discipline, depth/parallax, camera language in 2.5D, device/UI choreography (scroll speeds, tap feedback, zoom into UI elements, screen-to-fullscreen transitions), texture (grain, glow, chromatic aberration amounts), sound-picture sync, pacing curve over a 45 s spot (hook in first 2 s, peak, breath, CTA). Cite sources inline. Return a dense markdown "craft bible" (max ~1700 words) with numbered rules + "what separates great from good" + 12 signature techniques worth stealing (each with how to build it in HTML/GSAP/canvas).`, { label: 'research:craft', phase: 'Research' }),
  () => agent(`Read the existing knowledge in this repo and summarize what a new PurePeptide motion-design ad must reuse or avoid. Read: ${ROOT}/recherche-pubs/*.md (all four), ${ROOT}/reference-trendtrack/ANALYSE.md, ${ROOT}/purepeptide-neon-fr/{README.md,SCENES.md}, ${ROOT}/purepeptide-proof-en/README.md, ${ROOT}/purepeptide-film-en/{README.md,SCENES.md}, and skim ${ROOT}/purepeptide-neon-fr/js/lib.js and ${ROOT}/purepeptide-film-en/js/film.js (list every reusable helper with a one-line description). Inventory every reusable ASSET with absolute paths and what it looks like: brand SVGs (purepeptide-film-en/assets/brand), catalog vial PNGs with alpha (purepeptide-film-en/assets/vials), AI photoreal clips (purepeptide-film-en/assets/plates/ai/*.mp4: use ffprobe for duration and extract one frame each with ffmpeg to /tmp to look at them), Blender stills, fonts (woff2 files in the repo), and every existing music file (*/assets/audio/music_raw.mp3: ffprobe duration; describe mood/BPM if a README says it) and SFX files. Also report the toolkit: "npx hyperframes --version" in ${ROOT}/purepeptide-film-en, the commands used to lint/snapshot/render/verify (tools/snap.sh, tools/verify_output.sh), measured render speed notes from READMEs, and python libs available (numpy, PIL, soundfile, faster_whisper). Do NOT launch Blender renders (CPU is reserved). Return markdown: (1) lessons learned (what worked, what the user criticised), (2) asset inventory table, (3) brand palette (exact hex from SVGs/CSS) + type, (4) reusable code helpers, (5) toolkit + commands + hard limits.`, { label: 'research:repo', phase: 'Research' }),
  () => agent(`You are a sound designer for premium motion-design ads. Research (WebSearch) how top motion pieces sync sound to picture (Apple, BUCK, ManvsMachine, Stripe): music structure for 45 s (BPM ranges, drop placement, silence before the logo), SFX vocabulary for UI/phone taps/glass/liquid/molecular motion (whooshes, risers, glass tinks, sub hits, UI clicks, tick counters, cash-register-free "add to cart" sounds), sonic logo design, mixing targets for online video (-14 LUFS, true peak -1 dBTP), VO ducking depths. Then read ${ROOT}/purepeptide-film-en/tools/mix_audio.py and tools/audiolib.py (our Python mixing/synthesis library) and list what it provides and which SFX can be synthesized with it. Listen-free analysis of existing music: for each ${ROOT}/*/assets/audio/music_raw.mp3 compute duration, tempo estimate and loudness curve with python (numpy/soundfile after ffmpeg decode; librosa if installed) and say which fits a premium 45 s motion piece best and where its drop/sections are. Also read the ElevenLabs model guide with creative_get_model_guide (load with ToolSearch "select:mcp__ElevenLabs__creative_get_model_guide") for the v4 speech model only — DO NOT call any generation tool (credits are restricted). Return markdown: music choice + edit plan, SFX list template (what to synthesize), v4 VO direction rules (which tags work, how to make it expressive and human, words/s pacing), recommended audio pipeline.`, { label: 'research:sound', phase: 'Research' }),
])
const [craft, repo, sound] = research
const R = `## CRAFT BIBLE (top studios)\n${craft}\n\n## REPO KNOWLEDGE + ASSETS + TOOLKIT\n${repo}\n\n## SOUND\n${sound}`
log('research done: ' + research.map(x => (x || '').length).join(', ') + ' chars')

phase('Concepts')
const ANGLES = [
  ['A', 'KINETIC TYPE x PRODUCT — Apple/Stripe-grade kinetic typography where words become objects: letters assemble into the vial, "99%" morphs into the purity line, the label is built from the type; object-led transitions only, every cut is a match or a morph; the type finally flows INTO the iPhone screen and becomes the live site.'],
  ['B', 'THE MOLECULAR WORLD — a science-as-art journey: we fly through a stylised molecular/lattice universe (abstract, NOT biological/body imagery) that resolves into the vial; proof shown as elegant data-viz (chromatogram peak drawn by light, counters, lab-grade grids); BUCK/ManvsMachine-level 2.5D depth; the lattice collapses into the iPhone glass for the shopping sequence.'],
  ['C', 'PROOF AS DESIGN SYSTEM — a bold graphic system (grid, modular shapes, brand blues, Swiss-style layout) that turns the brand promise into a rhythmic, music-driven sequence: each claim is a "module" that snaps, folds and transforms into the next; the modules fold into the iPhone and become the site\'s real UI; the offers land as a satisfying cart choreography and a sonic logo.'],
]
const concepts = await parallel(ANGLES.map(([id, angle]) => () => agent(`You are a creative director at a world-class motion studio. Write concept ${id} for a 45.0 s motion-design ad for PurePeptide.
ANGLE: ${angle}
${RULES}
Look at the real site captures listed in ${OUT}/assets/site/SITE.md if it exists yet (open the PNGs with Read to see them); otherwise assume standard pages (home hero, shop grid, product page with add-to-cart, cart with automatic bundle discount line).
Use this research:\n${R}\n
Deliver markdown with:
1. Title + one-line idea + why it would win an award.
2. Style frames in words (palette with hex, type, textures, lighting) for 4 key moments, one of them the iPhone sequence.
3. Voice-over script for ElevenLabs v4 WITH emotion tags (human, dynamic, NOT monotone; 75–95 words total; short lines; contrasts; the brand said at most twice), each line with target start time.
4. Shot-by-shot storyboard: 10–16 shots, each with start–end time (s, 30 fps grid), what is on screen, the exact motion (eases, durations, staggers), the transition INTO the next shot, the on-screen text, and the SFX/music hit. Mark which shots need canvas/WebGL, Blender, AI-video plates (we have photoreal clips of the real vial: turntable, hero push-in, cold frost backlight, smoky backlight, cap macro, shoulder macro), the catalog vial PNGs, or the iPhone contract.
5. Music plan (which existing track and how it is edited, or the one new generation) + 10 key SFX.
6. Build risks and how to de-risk.
Be specific enough that 10 animators could each build one shot without talking to each other.`, { label: 'concept:' + id, phase: 'Concepts' })))

phase('Judge')
const JUDGES = [
  ['craft', 'an Emmy/Annecy-level motion design director (BUCK/ManvsMachine/Apple). Score visual ambition, originality, transition craft, typographic quality, rhythm, and how premium and real the iPhone sequence will feel.'],
  ['ad', 'a performance-marketing creative strategist. Score hook in first 2 s, clarity for a prospect who knows nothing about peptides or lab testing, memorability of the brand, offer + CTA clarity (the iPhone/site sequence must make "go to purepeptide.care and the discount applies automatically" obvious), emotional arc of the VO.'],
  ['build', 'a senior creative technologist who will build it in HyperFrames/GSAP headless with SwiftShader (slow WebGL) and Blender CPU on a 4-CPU machine, with parallel agents. Score feasibility at premium quality, risk, ElevenLabs budget discipline, and compliance with the HARD RULES (any violation = score 0 for that concept).'],
]
const scoreSchema = { type: 'object', properties: { scores: { type: 'array', items: { type: 'object', properties: { concept: { type: 'string' }, score: { type: 'number' }, strengths: { type: 'string' }, weaknesses: { type: 'string' }, steal: { type: 'string' } }, required: ['concept', 'score', 'strengths', 'weaknesses', 'steal'] } }, verdict: { type: 'string' } }, required: ['scores', 'verdict'] }
const C = concepts.map((c, i) => `=== CONCEPT ${ANGLES[i][0]} ===\n${c}`).join('\n\n')
const verdicts = await parallel(JUDGES.map(([k, who]) => () => agent(`You are ${who}\n${RULES}\nScore each concept 0–10 (decimals ok). List strengths, weaknesses and the single best idea worth stealing from it.\n\n${C}`, { label: 'judge:' + k, phase: 'Judge', schema: scoreSchema })))
const tally = {}
verdicts.filter(Boolean).forEach(v => v.scores.forEach(s => { const key = s.concept.replace(/[^ABC]/g, '').slice(0, 1) || s.concept; tally[key] = (tally[key] || 0) + s.score }))
log('tally ' + JSON.stringify(tally))

phase('Bible')
const bible = await agent(`You are the director. Synthesize the final production bible for the PurePeptide 45 s motion-design ad from the concepts and the judges' verdicts below. Start from the highest-scoring concept (tally: ${JSON.stringify(tally)}), graft the best "steal" ideas from the others, and fix every weakness the judges raised. ${RULES}

Before writing, open ${OUT}/assets/site/SITE.md and the site PNGs it lists (Read them) and ${OUT}/assets/iphone/ (README or PHONE.md, screen_rect.json, test renders) if present, so the iPhone scenes use the real pixel coordinates of buttons / prices / the discount line.

Write two files (create the directory ${OUT} first if needed):
1) ${OUT}/BRIEF.md — idea, tone, palette (hex), typography (fonts available as local woff2 in the repo — check ${ROOT}/purepeptide-film-en/assets/fonts and ${ROOT}/purepeptide-neon-fr/assets; the site itself uses DM Sans + Inter), texture, the craft rules to apply (cite the research), the final VO script for ElevenLabs v4 with emotion tags and per-line target start times (75–95 words), music plan (which file, edit points with timestamps, silence before logo) and SFX list with timestamps (synthesized locally), compliance checklist.
2) ${OUT}/SCENES.md — the production contract for parallel builders: global setup (1920x1080, 30 fps, 45.00 s, one paused GSAP timeline at absolute seconds, deterministic; per-scene files js/scenes/<id>.js exporting a function build(tl, root) that adds its tweens at absolute times, css/<id>.css, markup in html/<id>.html fragments; a shared js/lib.js adapted from ${ROOT}/purepeptide-neon-fr/js/lib.js; VO word timings will be available as window.VO.w(lineId, wordIndex) so text can sync to spoken words), and 8–12 scenes, each with: id, clip window [in,out] (scenes may overlap by a few frames for transitions), exact content, assets (absolute paths), motion spec (eases, durations, staggers, camera), transition in/out contract with neighbours (what the last frame of scene N must look like so N+1 can match-cut/morph from it), on-screen text, the sound events to land on (s, ±1 frame), and which tool. Each scene must be buildable by one agent independently. The iPhone scenes must specify phone placement/scale over time, which site capture is on screen when, scroll offsets in capture pixels, tap points (in capture pixels), and the cart discount moment.
Return a 15-line summary of the final concept and the scene list.

CONCEPTS:\n${C}\n\nVERDICTS:\n${JSON.stringify(verdicts, null, 1)}\n\nRESEARCH (for reference):\n${R}`, { label: 'bible', phase: 'Bible' })
return { tally, bible, research_lengths: research.map(x => (x || '').length) }
