export const meta = {
  name: 'pp-motion-build',
  description: 'Build the PurePeptide 45 s "Spelled out" motion ad: P0 setup (scaffold, clean site, blank fly-in, audio), 11 scenes built and polished in parallel, then integration QC',
  phases: [
    { title: 'Setup', detail: 'scaffold + rigs, clean site recapture, blank-screen fly-in, audio mix' },
    { title: 'Scenes', detail: 'one builder per scene, then an adversarial polish pass each' },
    { title: 'Integrate', detail: 'full-timeline QC gates, joins, compliance, draft render' },
  ],
}

const ROOT = '/home/user/DevDoctor/ads/purepeptide-motion-en'
const COMMON = `Project: ${ROOT}. READ FIRST: ${ROOT}/BRIEF.md and ${ROOT}/SCENES.md (the binding build contract; §0 global setup and your section). Reference implementation of the same toolchain: /home/user/DevDoctor/ads/purepeptide-film-en (index generator, tools/snap.sh, verify_output.sh, mix_audio.py, audiolib.py) and /home/user/DevDoctor/ads/purepeptide-neon-fr/js/lib.js. HyperFrames CLI via "npx hyperframes" (node_modules symlink to /home/user/DevDoctor/ads/purepeptide-30s-saas/node_modules). The skills hyperframes-core / hyperframes-animation / hyperframes-cli can be loaded with the Skill tool if you need API details.
FACTS THAT OVERRIDE THE DOCS:
- The real ElevenLabs v4 VO already exists: ${ROOT}/js/vo.js (window.VO, generated by tools/build_vo.py; the take is sped up 7 %). Several lines slid later than the BRIEF §6 targets: L05 9.81, L06 11.76 ("by Janoshik Analytical" part starts 13.60), L07 15.29 ("to ten countries" 17.46), L08 18.56, L09 20.83, L14 31.77. ALWAYS read word times with VO.w(id, i) — never hard-code word times. VO.w must also accept a word prefix string (SCENES §0.3). Music cues in js/cues.js are fixed.
- The machine has 4 CPUs shared with other agents: snapshot only the frames you need (tools/snap.sh), never run a full render unless your task says so, never run Blender unless your task says so.
- Never use git (the lead commits).
- Compliance (BRIEF §10) is absolute: no people/hands/fingers, no forbidden words, nothing from the raw/ site captures, only clean/ captures.`

phase('Setup')
const setup = await parallel([
  () => agent(`${COMMON}
YOUR TASK: P0-C, the project scaffold and shared rigs (SCENES §0.1–0.5, §0.8, §0.9; Appendix B tools). Build: package.json/hyperframes.json/meta.json, node_modules symlink, tools/assemble.py (index.html from html/<id>.html fragments + css/*.css + the stage video table §0.5 + scripts; video clips at stage level; asserts on seek limits), js/lib.js (adapted per §0.2), js/cues.js, css/tokens.css, js/phone.js (the full iPhone rig API of §0.4: PH.cam, PH.stage, PH.show, PH.scroll, PH.flick, PH.tap, PH.press, PH.push, PH.navBadge, PH.barFill, PH.crop — seek-safe), js/main.js, the global layers #world/#phone/#fx (grain+vignette per BRIEF §4), copy fonts/grain/vials/brand SVGs/AI plates (BRIEF §3, SCENES P0-C), tools/snap.sh, tools/verify_output.sh (1350 frames, 45.00 s), tools/check_text.js, tools/qc_frames.sh. For each scene S01..S11 create a stub html/<id>.html, css/<id>.css and js/scenes/<id>.js that only shows a centred label "<id>" in its window so the timeline is complete. The site screen points at assets/site/clean/ — if clean/ is not there yet, point at it anyway (another agent is producing it now; use the same file names as raw/: home.png, product.png, cart1.png, cart2.png, cart3.png, screen_blank.png). Remove will-change from phone-screen.css and replace backdrop-filter with the solid fill. Prove the rig: a temporary test (not shipped) showing the phone at REST with the home page, PROD and CART camera states, a tap ring and a push — snapshot and look at them. Finish with "npx hyperframes lint" at 0 errors and a snapshot at t=1,10,26,30 showing stubs. Write ${ROOT}/BUILD.md (how scenes plug in: exact helper signatures, z-indexes, how to snapshot one scene). Return a concise summary of the API.`, { label: 'P0-C scaffold+rigs', phase: 'Setup' }),
  () => agent(`${COMMON}
YOUR TASK: P0-A clean site recapture, then P0-B part 1 (screen_blank.png). Follow SCENES §0.6 and §0.7 rows P0-A / P0-B(1) exactly. Start from ${ROOT}/tools/capture_site.cjs (it already passes the researcher gate, adds 3 vials of the SAME compound, captures cart1/2/3 and product_2/3) and write ${ROOT}/tools/capture_clean.cjs; look at /home/user/DevDoctor/ads/purepeptide-proof-en/tools/record_site.cjs for MASK/hideRecon. Hide with visibility:hidden (coordinates unchanged): home hero lede (certificate), .hero__jano, .pd__cat, .pd__coa, .pd__pairs, .pp-express, .cart-addon, every SECURE CHECKOUT marquee item, freeze the marquee. The "product" page for the ad must show the "3+ vials −8%" bundle selected? NO — SCENES S07 decides the state: read S07/S08 and capture every state they need (e.g. product with 1 vial and with 3+ selected, add-to-cart notice, cart1/2/3). Paint/crop as specified. Output ${ROOT}/assets/site/clean/*.png + clean/meta.json + screen_blank.png. QC: build a contact sheet and LOOK at every page (Read the images); OCR (tesseract if installed, else visually) must find none of: certif|COA|bacterio|reconstitut|Retatrutide|Recovery|repair|G Pay|Pharmaceutical|SECURE|MT-2. Also verify the cart prices/discount lines/free-shipping texts are present and measure the ship-bar rect and fill fractions (SCENES §0.4 PH.barFill) and write them into clean/meta.json. Then render screen stills with tools/render_screens.cjs pointed at clean/ (screen_home.png etc. into clean/). Return what was captured, measured numbers, and the QC result.`, { label: 'P0-A clean site', phase: 'Setup' }),
])
log('setup 1: ' + setup.map(x => (x || 'NULL').slice(0, 80)).join(' | '))

const setup2 = await parallel([
  () => agent(`${COMMON}
YOUR TASK: P0-B parts 2–4: the blank-screen fly-in. ${ROOT}/assets/site/clean/screen_blank.png should now exist (if not, build it per SCENES P0-B(1) yourself). Render with ${ROOT}/assets/iphone/tools/render_iphone.py flyin --screen <abs path to screen_blank.png> --out renders/flyin_blank (Blender venv /home/user/DevDoctor/ads/purepeptide-blender/.venv/bin/python; read assets/iphone/PHONE.md; ONE Blender process, ~11 min). Retime to 68 frames exactly as SCENES P0-B(3) and encode assets/iphone/flyin_land.webm (VP9 alpha, crf 18). QC frame 89 vs the 2D rig stack (P0-B(4)). Look at frames 0/20/40/67 yourself. Update PHONE.md. Return results.`, { label: 'P0-B blank fly-in', phase: 'Setup' }),
  () => agent(`${COMMON}
YOUR TASK: P0-D audio (BRIEF §7 music + §8 SFX + mix; SCENES Appendix A). Copy audiolib.py and mix_audio.py from the film-en tools into ${ROOT}/tools/ and rewrite mix_audio.py for this film: the music edit from film-en music_raw.mp3 (EDIT table, -3 dB, silence rules), the library retune, every SFX of BRIEF §8 synthesized (new functions where noted, seeded), VO from assets/audio/vo/lines.tsv (clips already cut), ducking, master to -14.0 LUFS / <= -1.5 dBTP, output assets/audio/mix.wav (48 kHz, 24-bit, exactly 45.000 s) and a --report mode (VO-to-music margin per word, loudness, true peak). SFX times must come from js/cues.js and js/vo.js (parse them in Python) or from frame numbers in BRIEF/SCENES — keep a single table SFX_EVENTS in the script so the integration step can re-time events after picture lock. No ElevenLabs calls at all. Listen-free QC: plot/print RMS per 0.5 s, check silence windows (T 44–45, stop beat 40.5–41), and run the report. Return the report.`, { label: 'P0-D audio', phase: 'Setup' }),
])
log('setup 2: ' + setup2.map(x => (x || 'NULL').slice(0, 80)).join(' | '))

phase('Scenes')
const SCENES = ['S01', 'S02', 'S03', 'S04', 'S05', 'S06', 'S07', 'S08', 'S09', 'S10', 'S11']
const built = await pipeline(SCENES,
  id => agent(`${COMMON}
Also read ${ROOT}/BUILD.md (the scaffold's API, written by the lead) and look at the existing stubs.
YOUR TASK: build scene ${id} exactly as its section in SCENES.md specifies (window, content, motion spec with eases/durations/staggers, hand-off frames with neighbours, text, sound-event frames, tool). Edit ONLY html/${id}.html, css/${id}.css, js/scenes/${id}.js and any new asset/tool files your section owns (e.g. S02 owns P0-E typevial; S03/S04 own P0-F frost/glyph data). Use the shared helpers (PP.*, PH.*) — if a helper is missing or buggy, implement a local version inside your scene file rather than editing lib.js/phone.js, and say so in your reply. World-class bar: this must look like BUCK / ManvsMachine / Apple launch-film craft — precise easing, no dead frames, crisp type, depth, nothing amateur. Then run python3 tools/assemble.py, npx hyperframes lint (0 errors in your files), and snapshot your window densely (every ~0.25 s plus every hand-off frame) with tools/snap.sh; LOOK at every snapshot with Read and iterate until it is right: text >= 24 px rendered, contrast, title-safe, no clipping, no overlap mistakes, hand-off frames matching the contract. Return: what you built, the frames you checked, deviations from the spec and why, and anything the neighbours must know.`, { label: 'build:' + id, phase: 'Scenes' }),
  (rep, id) => agent(`${COMMON}
Also read ${ROOT}/BUILD.md.
YOUR TASK: adversarial polish of scene ${id} (its SCENES.md section). The builder reported:\n${(rep || '').slice(0, 3000)}\n
Snapshot the scene's window at 0.2 s steps plus every hand-off and sound-event frame (tools/snap.sh), view every frame, and hunt for: deviations from the spec, timing not locked to VO.w/cues, mushy or default easing, things moving all at once, dead holds, text under 24 px or low contrast or outside title-safe, jaggies/blur on type, hard pops or flashes, mismatched hand-off with neighbours (snapshot the 3 frames on each side of ${id}'s in/out), compliance violations (BRIEF §10 — any forbidden word or raw/ capture is a blocker). FIX every issue directly in ${id}'s own files (html/css/js of ${id} only), re-assemble, re-lint, re-snapshot and confirm. Also make one deliberate quality upgrade that raises it towards award level (a better transition detail, a micro-overshoot, a light sweep, depth parallax — within the spec's intent). Return the list of issues found and fixed, and anything unresolved.`, { label: 'polish:' + id, phase: 'Scenes' }),
)
log('scenes done: ' + built.map((x, i) => SCENES[i] + (x ? '' : ' FAILED')).join(', '))

phase('Integrate')
const integ = await agent(`${COMMON}
Also read ${ROOT}/BUILD.md.
YOUR TASK: integration and QC of the full 45 s film. Scene polish reports:\n${built.map((x, i) => '### ' + SCENES[i] + '\n' + (x || 'FAILED').slice(0, 1500)).join('\n')}\n
1. python3 tools/assemble.py; npx hyperframes lint and npx hyperframes check: 0 errors.
2. Snapshot every scene join (3 frames each side) and every 0.5 s across 0–45 s; view them all; fix broken joins, z-order, world crossfades (#world INK→PAPER→NAVY), the phone rig hand-offs (fly-in f749 → rig f750 must be invisible; DIVE at f1086), grain/vignette per world.
3. Run the SCENES Appendix B QC gates: tools/check_text.js (>= 24 px, >= 4.5:1, title-safe) and tools/qc_frames.sh (OCR forbidden words over T 22–37 and the whole film). Fix every failure in the owning scene file.
4. Re-time the SFX table in tools/mix_audio.py to the final picture frames (Appendix A) and re-run it; verify the report (VO >= 8 dB over music, -14 LUFS, TP <= -1.5).
5. Draft render: npx hyperframes render --quality draft -o renders/draft.mp4, remux assets/audio/mix.wav, run tools/verify_output.sh on it, and extract a contact sheet (1 frame per second) — view it.
Return: QC results (numbers), what you fixed, and any remaining issue ranked by severity.`, { label: 'integrate', phase: 'Integrate' })
return { setup, setup2, scenes: built.map((x, i) => SCENES[i] + ': ' + (x || 'FAILED').slice(0, 600)), integ }
