#!/usr/bin/env bash
# S02 / P0-E: (re)build the type-vial plate. Re-run after the VO, silhouette or S01's outline change (~2–4 min).
#   1. tools/trace_vial.py             -> assets/typevial/silhouette.{json,js}  (only if missing, or FORCE_TRACE=1)
#   2. assets/s01/outline.json         -> sub/typevial/s01.js  (S01's exact OUT frame: outline + clean "pure")
#   3. tools/typevial_density.mjs      -> assets/typevial/density.json (glyphs landed per plate frame, for the SFX)
#   4. hyperframes render sub/typevial -> assets/plates/typevial.mp4 (174 f, f105–f278, #000, crf 12)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
[ -f assets/typevial/silhouette.js ] && [ -z "${FORCE_TRACE:-}" ] || python3 tools/trace_vial.py
python3 - <<'PY'
import json
J = json.load(open('assets/s01/outline.json'))
open('sub/typevial/s01.js', 'w').write('// GENERATED by tools/render_typevial.sh from assets/s01/outline.json (S01 OUT frame)\nwindow.S01 = ' + json.dumps(J) + ';\n')
PY
python3 tools/s02_build.py
node tools/typevial_density.mjs
npx hyperframes render sub/typevial --crf 12 --workers "${WORKERS:-2}" --quiet -o assets/plates/typevial.mp4
ffprobe -v error -select_streams v:0 -show_entries stream=width,height,nb_frames,r_frame_rate,pix_fmt -of compact assets/plates/typevial.mp4
