#!/usr/bin/env python3
"""S02: writes html/S02.html (the light band + its silhouette clip) from assets/typevial/silhouette.json.
Re-run after tools/trace_vial.py (tools/render_typevial.sh does it). The band config (vial axis, band half-travel and
the hero push) rides in data-cfg so js/scenes/S02.js and sub/typevial/typevial.js share one geometry."""
import json, os
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
J = json.load(open(os.path.join(ROOT, 'assets/typevial/silhouette.json')))
cfg = dict(axis=J['axis_src'], half=300, push=[[p['s'], p['tx'], p['ty']] for p in J['push']])
html = f'''<!-- S02 · type-vial · f105–f278. GENERATED by tools/s02_build.py from assets/typevial/silhouette.json.
     The type-vial itself is the stage video v-typevial (assets/plates/typevial.mp4, tools/render_typevial.sh).
     This fragment holds the f262–f278 light band, clipped to the real vial (hero.mp4 geometry, driven by its push). -->
<svg class="s02-band" width="1920" height="1080" viewBox="0 0 1920 1080" aria-hidden="true" data-cfg='{json.dumps(cfg, separators=(",", ":"))}'>
  <defs>
    <clipPath id="s02-clip" clipPathUnits="userSpaceOnUse"><path d="{J['outline_d_src']}" /></clipPath>
    <linearGradient id="s02-beam-g" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#FFFFFF" stop-opacity="0" />
      <stop offset=".38" stop-color="#FFFFFF" stop-opacity=".55" />
      <stop offset=".5" stop-color="#FFFFFF" stop-opacity="1" />
      <stop offset=".62" stop-color="#FFFFFF" stop-opacity=".55" />
      <stop offset="1" stop-color="#FFFFFF" stop-opacity="0" />
    </linearGradient>
  </defs>
  <g class="s02-cam" clip-path="url(#s02-clip)"><rect class="s02-beam" x="0" y="0" width="220" height="1080" fill="url(#s02-beam-g)" /></g>
</svg>
'''
open(os.path.join(ROOT, 'html/S02.html'), 'w').write(html)
print('html/S02.html written')
