// Voice-over (English, Kokoro-82M « af_heart », one file per line): placement + word onsets. Generated by tools/build_vo.py.
window.PP = window.PP || {};
PP.VO = [
 {
  "id": "L01",
  "file": "assets/audio/vo/L01.wav",
  "src": [
   0.03,
   2.63
  ],
  "at": 2.6,
  "text": "Anyone can print 99% on a label.",
  "words": [
   {
    "w": "Anyone",
    "t0": 2.6,
    "t1": 2.83
   },
   {
    "w": "can",
    "t0": 2.83,
    "t1": 3.11
   },
   {
    "w": "print",
    "t0": 3.11,
    "t1": 3.39
   },
   {
    "w": "99%",
    "t0": 3.39,
    "t1": 4.43
   },
   {
    "w": "on",
    "t0": 4.43,
    "t1": 4.69
   },
   {
    "w": "a",
    "t0": 4.69,
    "t1": 4.79
   },
   {
    "w": "label.",
    "t0": 4.79,
    "t1": 4.99
   }
  ],
  "end": 5.2
 },
 {
  "id": "L02",
  "file": "assets/audio/vo/L02.wav",
  "src": [
   0.06,
   1.87
  ],
  "at": 5.8,
  "text": "Anyone can say “lab tested.”",
  "words": [
   {
    "w": "Anyone",
    "t0": 5.8,
    "t1": 6.02
   },
   {
    "w": "can",
    "t0": 6.02,
    "t1": 6.22
   },
   {
    "w": "say",
    "t0": 6.22,
    "t1": 6.48
   },
   {
    "w": "“lab",
    "t0": 6.58,
    "t1": 6.98
   },
   {
    "w": "tested.”",
    "t0": 6.98,
    "t1": 7.34
   }
  ],
  "end": 7.61
 },
 {
  "id": "L03",
  "file": "assets/audio/vo/L03.wav",
  "src": [
   0.09,
   1.76
  ],
  "at": 8.4,
  "text": "Almost no one shows you the proof.",
  "words": [
   {
    "w": "Almost",
    "t0": 8.4,
    "t1": 8.63
   },
   {
    "w": "no",
    "t0": 8.63,
    "t1": 8.85
   },
   {
    "w": "one",
    "t0": 8.85,
    "t1": 9.09
   },
   {
    "w": "shows",
    "t0": 9.09,
    "t1": 9.33
   },
   {
    "w": "you",
    "t0": 9.33,
    "t1": 9.53
   },
   {
    "w": "the",
    "t0": 9.53,
    "t1": 9.67
   },
   {
    "w": "proof.",
    "t0": 9.67,
    "t1": 9.83
   }
  ],
  "end": 10.07
 },
 {
  "id": "L04",
  "file": "assets/audio/vo/L04.wav",
  "src": [
   0.04,
   0.6
  ],
  "at": 12.3,
  "text": "We do.",
  "words": [
   {
    "w": "We",
    "t0": 12.3,
    "t1": 12.42
   },
   {
    "w": "do.",
    "t0": 12.42,
    "t1": 12.5
   }
  ],
  "end": 12.86
 },
 {
  "id": "L05",
  "file": "assets/audio/vo/L05.wav",
  "src": [
   0.03,
   2.26
  ],
  "at": 17.3,
  "text": "Every batch, sent to an independent lab.",
  "words": [
   {
    "w": "Every",
    "t0": 17.3,
    "t1": 17.45
   },
   {
    "w": "batch,",
    "t0": 17.45,
    "t1": 17.73
   },
   {
    "w": "sent",
    "t0": 17.73,
    "t1": 18.23
   },
   {
    "w": "to",
    "t0": 18.23,
    "t1": 18.43
   },
   {
    "w": "an",
    "t0": 18.43,
    "t1": 18.55
   },
   {
    "w": "independent",
    "t0": 18.55,
    "t1": 18.81
   },
   {
    "w": "lab.",
    "t0": 18.81,
    "t1": 19.23
   }
  ],
  "end": 19.53
 },
 {
  "id": "L06",
  "file": "assets/audio/vo/L06.wav",
  "src": [
   0.1,
   1.42
  ],
  "at": 20.0,
  "text": "Identity, confirmed.",
  "words": [
   {
    "w": "Identity,",
    "t0": 20.0,
    "t1": 20.48
   },
   {
    "w": "confirmed.",
    "t0": 20.48,
    "t1": 20.76
   }
  ],
  "end": 21.32
 },
 {
  "id": "L07",
  "file": "assets/audio/vo/L07.wav",
  "src": [
   0.03,
   0.96
  ],
  "at": 22.0,
  "text": "Purity, measured.",
  "words": [
   {
    "w": "Purity,",
    "t0": 22.0,
    "t1": 22.23
   },
   {
    "w": "measured.",
    "t0": 22.23,
    "t1": 22.65
   }
  ],
  "end": 22.93
 },
 {
  "id": "L08",
  "file": "assets/audio/vo/L08.wav",
  "src": [
   0.05,
   1.91
  ],
  "at": 23.5,
  "text": "99%. Minimum.",
  "words": [
   {
    "w": "99%.",
    "t0": 23.5,
    "t1": 24.29
   },
   {
    "w": "Minimum.",
    "t0": 24.29,
    "t1": 24.99
   }
  ],
  "end": 25.36
 },
 {
  "id": "L09",
  "file": "assets/audio/vo/L09.wav",
  "src": [
   0.04,
   2.12
  ],
  "at": 26.0,
  "text": "Shipped cold, within 24 hours.",
  "words": [
   {
    "w": "Shipped",
    "t0": 26.0,
    "t1": 26.24
   },
   {
    "w": "cold,",
    "t0": 26.24,
    "t1": 26.52
   },
   {
    "w": "within",
    "t0": 26.52,
    "t1": 26.96
   },
   {
    "w": "24",
    "t0": 26.96,
    "t1": 27.36
   },
   {
    "w": "hours.",
    "t0": 27.36,
    "t1": 27.78
   }
  ],
  "end": 28.08
 },
 {
  "id": "L10",
  "file": "assets/audio/vo/L10.wav",
  "src": [
   0.07,
   1.43
  ],
  "at": 28.8,
  "text": "Don’t take our word for it.",
  "words": [
   {
    "w": "Don’t",
    "t0": 28.8,
    "t1": 29.05
   },
   {
    "w": "take",
    "t0": 29.05,
    "t1": 29.17
   },
   {
    "w": "our",
    "t0": 29.17,
    "t1": 29.39
   },
   {
    "w": "word",
    "t0": 29.39,
    "t1": 29.59
   },
   {
    "w": "for",
    "t0": 29.59,
    "t1": 29.81
   },
   {
    "w": "it.",
    "t0": 29.81,
    "t1": 29.97
   }
  ],
  "end": 30.16
 },
 {
  "id": "L11",
  "file": "assets/audio/vo/L11.wav",
  "src": [
   0.05,
   0.98
  ],
  "at": 30.6,
  "text": "Check it yourself.",
  "words": [
   {
    "w": "Check",
    "t0": 30.6,
    "t1": 30.81
   },
   {
    "w": "it",
    "t0": 30.81,
    "t1": 30.87
   },
   {
    "w": "yourself.",
    "t0": 30.87,
    "t1": 31.07
   }
  ],
  "end": 31.53
 },
 {
  "id": "L12",
  "file": "assets/audio/vo/L12.wav",
  "src": [
   0.04,
   1.07
  ],
  "at": 36.2,
  "text": "Pick your compound.",
  "words": [
   {
    "w": "Pick",
    "t0": 36.2,
    "t1": 36.32
   },
   {
    "w": "your",
    "t0": 36.32,
    "t1": 36.44
   },
   {
    "w": "compound.",
    "t0": 36.44,
    "t1": 36.8
   }
  ],
  "end": 37.23
 },
 {
  "id": "L13",
  "file": "assets/audio/vo/L13.wav",
  "src": [
   0.04,
   1.75
  ],
  "at": 39.2,
  "text": "See the purity. Verified.",
  "words": [
   {
    "w": "See",
    "t0": 39.2,
    "t1": 39.32
   },
   {
    "w": "the",
    "t0": 39.32,
    "t1": 39.42
   },
   {
    "w": "purity.",
    "t0": 39.42,
    "t1": 39.72
   },
   {
    "w": "Verified.",
    "t0": 39.72,
    "t1": 40.36
   }
  ],
  "end": 40.91
 },
 {
  "id": "L14",
  "file": "assets/audio/vo/L14.wav",
  "src": [
   0.03,
   0.53
  ],
  "at": 42.0,
  "text": "Order.",
  "words": [
   {
    "w": "Order.",
    "t0": 42.0,
    "t1": 42.29
   }
  ],
  "end": 42.5
 },
 {
  "id": "L15",
  "file": "assets/audio/vo/L15.wav",
  "src": [
   0.02,
   3.57
  ],
  "at": 42.8,
  "text": "Two vials, 5% off. Three or more, 8%.",
  "words": [
   {
    "w": "Two",
    "t0": 42.8,
    "t1": 42.92
   },
   {
    "w": "vials,",
    "t0": 42.92,
    "t1": 43.32
   },
   {
    "w": "5%",
    "t0": 43.36,
    "t1": 43.96
   },
   {
    "w": "off.",
    "t0": 43.96,
    "t1": 44.24
   },
   {
    "w": "Three",
    "t0": 44.64,
    "t1": 45.04
   },
   {
    "w": "or",
    "t0": 45.04,
    "t1": 45.16
   },
   {
    "w": "more,",
    "t0": 45.16,
    "t1": 45.32
   },
   {
    "w": "8%.",
    "t0": 45.48,
    "t1": 46.0
   }
  ],
  "end": 46.35
 },
 {
  "id": "L16",
  "file": "assets/audio/vo/L16.wav",
  "src": [
   0.05,
   1.88
  ],
  "at": 49.5,
  "text": "No promises. Just proof.",
  "words": [
   {
    "w": "No",
    "t0": 49.5,
    "t1": 49.67
   },
   {
    "w": "promises.",
    "t0": 49.67,
    "t1": 50.07
   },
   {
    "w": "Just",
    "t0": 50.39,
    "t1": 50.75
   },
   {
    "w": "proof.",
    "t0": 50.75,
    "t1": 51.07
   }
  ],
  "end": 51.33
 },
 {
  "id": "L18",
  "file": "assets/audio/vo/L18.wav",
  "src": [
   0.03,
   0.95
  ],
  "at": 52.4,
  "text": "PurePeptide.",
  "words": [
   {
    "w": "PurePeptide.",
    "t0": 52.4,
    "t1": 53.32
   }
  ],
  "end": 53.32
 },
 {
  "id": "L19",
  "file": "assets/audio/vo/L19.wav",
  "src": [
   0.04,
   1.07
  ],
  "at": 53.6,
  "text": "Purity, proven.",
  "words": [
   {
    "w": "Purity,",
    "t0": 53.6,
    "t1": 53.86
   },
   {
    "w": "proven.",
    "t0": 53.86,
    "t1": 54.34
   }
  ],
  "end": 54.63
 }
];
