// GENERATED by tools/build_vo.py — ElevenLabs v4 take (Markmont), word onsets on the video timeline (s).
window.VO = {
 "L01": {
  "at": 1.0,
  "end": 1.44,
  "text": "Pure.",
  "words": [
   [
    1.0,
    "Pure."
   ]
  ]
 },
 "L02": {
  "at": 2.4,
  "end": 6.69,
  "text": "It's such an easy word to print. And such a hard one to prove.",
  "words": [
   [
    2.4,
    "It's"
   ],
   [
    2.53,
    "such"
   ],
   [
    2.79,
    "an"
   ],
   [
    2.97,
    "easy"
   ],
   [
    3.37,
    "word"
   ],
   [
    3.73,
    "to"
   ],
   [
    3.91,
    "print"
   ],
   [
    4.19,
    "and"
   ],
   [
    4.95,
    "such"
   ],
   [
    5.23,
    "a"
   ],
   [
    5.37,
    "hard"
   ],
   [
    5.67,
    "one"
   ],
   [
    5.87,
    "to"
   ],
   [
    6.01,
    "prove."
   ]
  ]
 },
 "L03": {
  "at": 7.6,
  "end": 9.91,
  "text": "So we don't print it. We measure it.",
  "words": [
   [
    7.6,
    "So"
   ],
   [
    7.73,
    "we"
   ],
   [
    7.85,
    "don't"
   ],
   [
    8.11,
    "print"
   ],
   [
    8.31,
    "it,"
   ],
   [
    8.59,
    "we"
   ],
   [
    9.05,
    "measure"
   ],
   [
    9.47,
    "it."
   ]
  ]
 },
 "L04": {
  "at": 11.2,
  "end": 17.21,
  "text": "Every batch. Every single one. Tested independently. By Janoshik Analytical.",
  "words": [
   [
    11.2,
    "Every"
   ],
   [
    11.37,
    "batch."
   ],
   [
    11.89,
    "Every"
   ],
   [
    12.67,
    "single"
   ],
   [
    13.19,
    "one."
   ],
   [
    13.67,
    "Tested"
   ],
   [
    14.47,
    "independently"
   ],
   [
    14.93,
    "by"
   ],
   [
    15.83,
    "Janosik"
   ],
   [
    16.33,
    "Analytical."
   ]
  ]
 },
 "L05": {
  "at": 18.4,
  "end": 20.95,
  "text": "Ninety-nine percent. Minimum.",
  "words": [
   [
    18.4,
    "99"
   ],
   [
    18.99,
    "%"
   ],
   [
    19.59,
    "minimum."
   ]
  ]
 },
 "L06": {
  "at": 21.6,
  "end": 24.19,
  "text": "Shipped cold. Within twenty-four hours.",
  "words": [
   [
    21.6,
    "Shipped"
   ],
   [
    21.89,
    "cold"
   ],
   [
    22.19,
    "within"
   ],
   [
    22.87,
    "24"
   ],
   [
    23.39,
    "hours."
   ]
  ]
 },
 "L07": {
  "at": 25.6,
  "end": 27.86,
  "text": "Don't take our word for it. Open the site.",
  "words": [
   [
    25.6,
    "Don't"
   ],
   [
    25.75,
    "take"
   ],
   [
    25.85,
    "our"
   ],
   [
    26.01,
    "word"
   ],
   [
    26.23,
    "for"
   ],
   [
    26.43,
    "it."
   ],
   [
    26.77,
    "Open"
   ],
   [
    27.13,
    "the"
   ],
   [
    27.29,
    "site."
   ]
  ]
 },
 "L08": {
  "at": 29.0,
  "end": 31.27,
  "text": "Let the cart do the math. It's automatic.",
  "words": [
   [
    29.0,
    "Let"
   ],
   [
    29.07,
    "the"
   ],
   [
    29.21,
    "cart"
   ],
   [
    29.45,
    "do"
   ],
   [
    29.63,
    "the"
   ],
   [
    29.77,
    "math."
   ],
   [
    30.21,
    "It's"
   ],
   [
    30.57,
    "automatic."
   ]
  ]
 },
 "L09": {
  "at": 35.0,
  "end": 37.95,
  "text": "PurePeptide. Purity. Proven.",
  "words": [
   [
    35.0,
    "Pure"
   ],
   [
    35.27,
    "Peptide."
   ],
   [
    35.97,
    "Purity"
   ],
   [
    36.71,
    "Proven."
   ]
  ]
 },
 "L10": {
  "at": 40.5,
  "end": 42.04,
  "text": "purepeptide dot care",
  "words": [
   [
    40.5,
    "purepeptide"
   ],
   [
    41.27,
    ".care"
   ]
  ]
 }
};
window.VO.w = (id, i) => window.VO[id].words[i][0];
