// Voice-over (ElevenLabs eleven_v3, voice « Paul K — French Ad & Trailer »): cut in the take, placement on the
// 60 s timeline, word onsets (Whisper large-v3). Generated by tools/build_vo.py — do not edit.
window.PP = window.PP || {};
PP.VO = [
 {
  "id": "L1",
  "src": [
   0.0,
   1.47
  ],
  "at": 0.7,
  "text": "Vous en avez marre, hein ?",
  "words": [
   {
    "w": "Vous",
    "t0": 0.7,
    "t1": 1.16
   },
   {
    "w": "en",
    "t0": 1.16,
    "t1": 1.36
   },
   {
    "w": "avez",
    "t0": 1.36,
    "t1": 1.54
   },
   {
    "w": "marre,",
    "t0": 1.54,
    "t1": 1.92
   },
   {
    "w": "hein ?",
    "t0": 1.92,
    "t1": 2.17
   }
  ],
  "end": 2.17
 },
 {
  "id": "L2",
  "src": [
   2.2,
   4.62
  ],
  "at": 2.7,
  "text": "Marre des peptides vendus par de faux labos.",
  "words": [
   {
    "w": "Marre",
    "t0": 2.76,
    "t1": 3.06
   },
   {
    "w": "des",
    "t0": 3.06,
    "t1": 3.16
   },
   {
    "w": "peptides",
    "t0": 3.16,
    "t1": 3.6
   },
   {
    "w": "vendus",
    "t0": 3.6,
    "t1": 3.98
   },
   {
    "w": "par",
    "t0": 3.98,
    "t1": 4.18
   },
   {
    "w": "de",
    "t0": 4.18,
    "t1": 4.3
   },
   {
    "w": "faux",
    "t0": 4.3,
    "t1": 4.6
   },
   {
    "w": "labos.",
    "t0": 4.6,
    "t1": 5.12
   }
  ],
  "end": 5.12
 },
 {
  "id": "L3",
  "src": [
   4.9,
   7.5
  ],
  "at": 5.5,
  "text": "Des analyses… que personne ne montre.",
  "words": [
   {
    "w": "Des",
    "t0": 5.53,
    "t1": 5.76
   },
   {
    "w": "analyses…",
    "t0": 5.76,
    "t1": 6.18
   },
   {
    "w": "que",
    "t0": 6.18,
    "t1": 6.86
   },
   {
    "w": "personne",
    "t0": 6.9,
    "t1": 7.3
   },
   {
    "w": "ne",
    "t0": 7.3,
    "t1": 7.58
   },
   {
    "w": "montre.",
    "t0": 7.58,
    "t1": 8.1
   }
  ],
  "end": 8.1
 },
 {
  "id": "L4",
  "src": [
   7.88,
   10.18
  ],
  "at": 8.4,
  "text": "Des fioles… sans aucune preuve.",
  "words": [
   {
    "w": "Des",
    "t0": 8.43,
    "t1": 8.51
   },
   {
    "w": "fioles…",
    "t0": 8.5,
    "t1": 8.92
   },
   {
    "w": "sans",
    "t0": 8.92,
    "t1": 9.52
   },
   {
    "w": "aucune",
    "t0": 9.52,
    "t1": 10.0
   },
   {
    "w": "preuve.",
    "t0": 10.0,
    "t1": 10.7
   }
  ],
  "end": 10.7
 },
 {
  "id": "L5",
  "src": [
   11.5,
   12.16
  ],
  "at": 12.3,
  "text": "Nous aussi.",
  "words": [
   {
    "w": "Nous",
    "t0": 12.34,
    "t1": 12.48
   },
   {
    "w": "aussi.",
    "t0": 12.48,
    "t1": 12.96
   }
  ],
  "end": 12.96
 },
 {
  "id": "L6",
  "src": [
   12.64,
   13.79
  ],
  "at": 13.6,
  "text": "Alors on a fait autrement.",
  "words": [
   {
    "w": "Alors",
    "t0": 13.63,
    "t1": 13.74
   },
   {
    "w": "on",
    "t0": 13.74,
    "t1": 13.92
   },
   {
    "w": "a",
    "t0": 13.92,
    "t1": 14.04
   },
   {
    "w": "fait",
    "t0": 14.04,
    "t1": 14.18
   },
   {
    "w": "autrement.",
    "t0": 14.18,
    "t1": 14.75
   }
  ],
  "end": 14.75
 },
 {
  "id": "L7",
  "src": [
   14.48,
   16.98
  ],
  "at": 17.3,
  "text": "Chaque lot part dans un laboratoire indépendant.",
  "words": [
   {
    "w": "Chaque",
    "t0": 17.33,
    "t1": 17.56
   },
   {
    "w": "lot",
    "t0": 17.56,
    "t1": 17.74
   },
   {
    "w": "part",
    "t0": 17.74,
    "t1": 18.0
   },
   {
    "w": "dans",
    "t0": 18.0,
    "t1": 18.2
   },
   {
    "w": "un",
    "t0": 18.2,
    "t1": 18.38
   },
   {
    "w": "laboratoire",
    "t0": 18.38,
    "t1": 18.94
   },
   {
    "w": "indépendant.",
    "t0": 18.94,
    "t1": 19.8
   }
  ],
  "end": 19.8
 },
 {
  "id": "L8",
  "src": [
   17.4,
   19.01
  ],
  "at": 20.2,
  "text": "On vérifie que c’est le bon produit.",
  "words": [
   {
    "w": "On",
    "t0": 20.23,
    "t1": 20.31
   },
   {
    "w": "vérifie",
    "t0": 20.3,
    "t1": 20.64
   },
   {
    "w": "que",
    "t0": 20.64,
    "t1": 20.8
   },
   {
    "w": "c’est",
    "t0": 20.8,
    "t1": 21.0
   },
   {
    "w": "le",
    "t0": 21.0,
    "t1": 21.08
   },
   {
    "w": "bon",
    "t0": 21.07,
    "t1": 21.26
   },
   {
    "w": "produit.",
    "t0": 21.26,
    "t1": 21.81
   }
  ],
  "end": 21.81
 },
 {
  "id": "L9",
  "src": [
   19.35,
   20.47
  ],
  "at": 22.0,
  "text": "On mesure sa pureté.",
  "words": [
   {
    "w": "On",
    "t0": 22.03,
    "t1": 22.11
   },
   {
    "w": "mesure",
    "t0": 22.1,
    "t1": 22.35
   },
   {
    "w": "sa",
    "t0": 22.35,
    "t1": 22.55
   },
   {
    "w": "pureté.",
    "t0": 22.55,
    "t1": 23.12
   }
  ],
  "end": 23.12
 },
 {
  "id": "L10",
  "src": [
   21.1,
   23.3
  ],
  "at": 23.6,
  "text": "99 %, minimum.",
  "words": [
   {
    "w": "99 %,",
    "t0": 23.64,
    "t1": 24.48
   },
   {
    "w": "minimum.",
    "t0": 24.48,
    "t1": 25.59
   }
  ],
  "end": 25.8
 },
 {
  "id": "L11",
  "src": [
   23.96,
   26.42
  ],
  "at": 27.0,
  "text": "Et surtout… ne nous croyez pas sur parole.",
  "words": [
   {
    "w": "Et",
    "t0": 27.03,
    "t1": 27.11
   },
   {
    "w": "surtout…",
    "t0": 27.1,
    "t1": 27.54
   },
   {
    "w": "ne",
    "t0": 27.54,
    "t1": 28.08
   },
   {
    "w": "nous",
    "t0": 28.08,
    "t1": 28.22
   },
   {
    "w": "croyez",
    "t0": 28.22,
    "t1": 28.48
   },
   {
    "w": "pas",
    "t0": 28.48,
    "t1": 28.7
   },
   {
    "w": "sur",
    "t0": 28.7,
    "t1": 28.88
   },
   {
    "w": "parole.",
    "t0": 28.88,
    "t1": 29.41
   }
  ],
  "end": 29.46
 },
 {
  "id": "L12",
  "src": [
   27.13,
   27.65
  ],
  "at": 29.9,
  "text": "Testez !",
  "words": [
   {
    "w": "Testez !",
    "t0": 29.93,
    "t1": 30.42
   }
  ],
  "end": 30.42
 },
 {
  "id": "L13",
  "src": [
   28.07,
   29.48
  ],
  "at": 35.0,
  "text": "Choisissez votre référence.",
  "words": [
   {
    "w": "Choisissez",
    "t0": 35.03,
    "t1": 35.41
   },
   {
    "w": "votre",
    "t0": 35.41,
    "t1": 35.61
   },
   {
    "w": "référence.",
    "t0": 35.61,
    "t1": 36.41
   }
  ],
  "end": 36.41
 },
 {
  "id": "L14",
  "src": [
   29.7,
   31.57
  ],
  "at": 38.1,
  "text": "Regardez sa pureté, vérifiée.",
  "words": [
   {
    "w": "Regardez",
    "t0": 38.13,
    "t1": 38.56
   },
   {
    "w": "sa",
    "t0": 38.56,
    "t1": 38.64
   },
   {
    "w": "pureté,",
    "t0": 38.64,
    "t1": 39.1
   },
   {
    "w": "vérifiée.",
    "t0": 39.31,
    "t1": 39.97
   }
  ],
  "end": 39.97
 },
 {
  "id": "L15",
  "src": [
   32.27,
   32.86
  ],
  "at": 41.0,
  "text": "Commandez :",
  "words": [
   {
    "w": "Commandez :",
    "t0": 41.03,
    "t1": 41.59
   }
  ],
  "end": 41.59
 },
 {
  "id": "L16",
  "src": [
   33.03,
   35.53
  ],
  "at": 41.8,
  "text": "expédié sous 24 heures, vers 10 pays.",
  "words": [
   {
    "w": "expédié",
    "t0": 41.83,
    "t1": 42.27
   },
   {
    "w": "sous",
    "t0": 42.27,
    "t1": 42.47
   },
   {
    "w": "24",
    "t0": 42.47,
    "t1": 42.81
   },
   {
    "w": "heures,",
    "t0": 42.81,
    "t1": 43.21
   },
   {
    "w": "vers",
    "t0": 43.21,
    "t1": 43.57
   },
   {
    "w": "10",
    "t0": 43.57,
    "t1": 43.79
   },
   {
    "w": "pays.",
    "t0": 43.79,
    "t1": 44.28
   }
  ],
  "end": 44.3
 },
 {
  "id": "L17",
  "src": [
   36.45,
   37.27
  ],
  "at": 46.5,
  "text": "Pas de promesses.",
  "words": [
   {
    "w": "Pas",
    "t0": 46.53,
    "t1": 46.61
   },
   {
    "w": "de",
    "t0": 46.6,
    "t1": 46.68
   },
   {
    "w": "promesses.",
    "t0": 46.67,
    "t1": 47.32
   }
  ],
  "end": 47.32
 },
 {
  "id": "L18",
  "src": [
   37.48,
   38.25
  ],
  "at": 47.8,
  "text": "Des preuves.",
  "words": [
   {
    "w": "Des",
    "t0": 47.83,
    "t1": 47.91
   },
   {
    "w": "preuves.",
    "t0": 47.9,
    "t1": 48.57
   }
  ],
  "end": 48.57
 },
 {
  "id": "L19",
  "src": [
   39.16,
   39.95
  ],
  "at": 49.5,
  "text": "PurePeptide.",
  "words": [
   {
    "w": "PurePeptide.",
    "t0": 49.53,
    "t1": 50.29
   }
  ],
  "end": 50.29
 },
 {
  "id": "L20",
  "src": [
   40.17,
   41.52
  ],
  "at": 50.8,
  "text": "La pureté, prouvée.",
  "words": [
   {
    "w": "La",
    "t0": 50.83,
    "t1": 50.91
   },
   {
    "w": "pureté,",
    "t0": 50.9,
    "t1": 51.45
   },
   {
    "w": "prouvée.",
    "t0": 51.72,
    "t1": 52.15
   }
  ],
  "end": 52.15
 }
];
