#!/usr/bin/env python3
"""js/vo.js from the chosen take (assets/audio/vo.mp3 = ElevenLabs v3, voice « Paul K — French Ad & Trailer »).
Line cuts = measured silences in the take; word onsets = Whisper large-v3 pushed out of silences;
placement = the 60 s edit (music drop at 17.00 s, beats every 0.5 s after it)."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
words = json.load(open(ROOT / "tools/vo_words_whisper.json"))
SIL = [(1.47,1.91),(1.97,2.24),(4.62,4.93),(5.95,6.30),(7.50,7.91),(8.64,8.91),(10.18,11.54),(12.16,12.67),(13.79,14.51),
       (16.98,17.43),(19.01,19.38),(20.47,21.14),(22.40,22.60),(23.30,23.99),(24.65,25.01),(26.42,27.16),(27.65,28.10),
       (29.48,29.73),(30.76,30.91),(31.57,32.30),(32.86,33.06),(35.53,36.48),(37.27,37.51),(38.25,39.19),(39.95,40.20),(40.90,41.09)]
LINES = [  # id, [src0, src1] in the take, video time, display text
 ("L1",  (0.00, 1.47), 0.70, "Vous en avez marre, hein ?"),
 ("L2",  (2.20, 4.62), 2.70, "Marre des peptides vendus par de faux labos."),
 ("L3",  (4.90, 7.50), 5.50, "Des analyses… que personne ne montre."),
 ("L4",  (7.88, 10.18), 8.40, "Des fioles… sans aucune preuve."),
 ("L5",  (11.50, 12.16), 12.30, "Nous aussi."),
 ("L6",  (12.64, 13.79), 13.60, "Alors on a fait autrement."),
 ("L7",  (14.48, 16.98), 17.30, "Chaque lot part dans un laboratoire indépendant."),
 ("L8",  (17.40, 19.01), 20.20, "On vérifie que c’est le bon produit."),
 ("L9",  (19.35, 20.47), 22.00, "On mesure sa pureté."),
 ("L10", (21.10, 23.30), 23.60, "99 %, minimum."),
 ("L11", (23.96, 26.42), 27.00, "Et surtout… ne nous croyez pas sur parole."),
 ("L12", (27.13, 27.65), 29.90, "Testez !"),
 ("L13", (28.07, 29.48), 35.00, "Choisissez votre référence."),
 ("L14", (29.70, 31.57), 38.10, "Regardez sa pureté, vérifiée."),
 ("L15", (32.27, 32.86), 41.00, "Commandez :"),
 ("L16", (33.03, 35.53), 41.80, "expédié sous 24 heures, vers 10 pays."),
 ("L17", (36.45, 37.27), 46.50, "Pas de promesses."),
 ("L18", (37.48, 38.25), 47.80, "Des preuves."),
 ("L19", (39.16, 39.95), 49.50, "PurePeptide."),
 ("L20", (40.17, 41.52), 50.80, "La pureté, prouvée."),
]
FIX = {"Regardez": 29.73, "Expédiez": 33.06, "La": 40.20}  # Whisper places it inside the 29.48-29.73 pause
toks = []
for t0, t1, w in words:
    t0 = FIX.get(w, t0)
    if toks and (w in ("?", "!", ".", ",", ":") or w.startswith("'") or w.startswith("-") or w in ("%", "%,") or (toks[-1][2] == "Pure" and w.startswith("Peptide"))):
        toks[-1] = [toks[-1][0], t1, toks[-1][2] + w]
    else:
        toks.append([t0, t1, w])
def unsil(t):
    for a, b in SIL:
        if a - 0.08 <= t < b: return b
    return t
out = []
for lid, (s0, s1), at, text in LINES:
    lw = [w for w in toks if s0 - 0.05 <= unsil(w[0]) < s1]
    disp = []
    for d in text.split(" "):
        if disp and d in ("?", "!", ":", ";"): disp[-1] += " " + d
        else: disp.append(d)
    if lid == "L10": disp = ["99 %,", "minimum."]
    assert len(lw) == len(disp), (lid, [w[2] for w in lw], disp)
    sh = at - s0
    ws = []
    for i, (w, d) in enumerate(zip(lw, disp)):
        t0 = max(unsil(w[0]), s0, (ws[-1]["t0"] - sh + 0.07) if ws else 0)
        t1 = lw[i + 1][0] if i + 1 < len(lw) else min(w[1] + 0.25, s1)
        ws.append({"w": d, "t0": round(t0 + sh, 3), "t1": round(max(t1, t0 + 0.08) + sh, 3)})
    out.append({"id": lid, "src": [s0, s1], "at": at, "text": text, "words": ws, "end": round(at + s1 - s0, 3)})
for a, b in zip(out, out[1:]):
    assert b["at"] >= a["end"] - 1e-6, (a["id"], b["id"])
js = "// Voice-over (ElevenLabs eleven_v3, voice « Paul K — French Ad & Trailer »): cut in the take, placement on the\n// 60 s timeline, word onsets (Whisper large-v3). Generated by tools/build_vo.py — do not edit.\nwindow.PP = window.PP || {};\nPP.VO = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n"
(ROOT / "js/vo.js").write_text(js)
for l in out: print(l["id"], l["at"], "->", l["end"], " | ".join(f'{w["w"]}@{w["t0"]}' for w in l["words"]))
