// PurePeptide — 60 s product film. One paused GSAP timeline, absolute seconds (SCENES.md EDL).
// Timed windows (hard cuts) live in index.html (generated by tools/gen_index.py); this file builds each shot's
// content and its motion. Every visual state is a pure function of timeline time (no clocks, no Math.random).
(function () {
  const PP = window.PP;
  const FILM = (window.FILM = {});
  const B = 1920 / 2112; // plates are 2112 px wide (10 % push headroom): scale B = exact fill
  const P = (n) => "assets/plates/" + n + ".jpg";
  const $ = (id) => document.getElementById(id);

  // ------------------------------------------------------------ helpers
  // plate: image in a shot, with a move from {s,x,y} to {s,x,y} across [t0, t1] (s relative to fill)
  function plate(tl, shot, src, t0, t1, a, b, ease, cls) {
    const img = PP.el("img", "plate" + (cls ? " " + cls : ""), shot, { src, alt: "" });
    b = b || a;
    tl.fromTo(img, { scale: B * (a.s || 1), x: a.x || 0, y: a.y || 0 }, { scale: B * (b.s || 1), x: b.x || 0, y: b.y || 0, duration: t1 - t0, ease: ease || "none", immediateRender: true }, t0);
    return img;
  }
  // video clip move (the <video> is a stage-level clip; only its transform is tweened)
  function vmove(tl, id, t0, t1, a, b, ease) {
    const v = $(id);
    tl.fromTo(v, { scale: a.s || 1, x: a.x || 0, y: a.y || 0 }, { scale: b.s || 1, x: b.x || 0, y: b.y || 0, duration: t1 - t0, ease: ease || "none", immediateRender: true }, t0);
  }
  // pushes are given in %/s: s(t) = 1 + rate * (t - t0)
  const push = (rate, dur, base) => [{ s: base || 1 }, { s: (base || 1) * (1 + (rate / 100) * dur) }];

  // text block: lines of words; returns word spans. Words enter one by one (Apple: opacity in ~3 frames, tiny settle).
  function words(parent, lines, style) {
    const box = PP.el("div", "t", parent, { style });
    const ws = [];
    lines.forEach((line) => {
      const ln = PP.el("span", "ln", box);
      line.split(" ").forEach((w, i) => {
        if (i) ln.appendChild(document.createTextNode(" "));
        ws.push(PP.el("span", "w", ln, { text: w }));
      });
    });
    return { box, ws };
  }
  function wordIn(tl, w, at) {
    tl.fromTo(w, { opacity: 0 }, { opacity: 1, duration: 0.1, ease: "none", immediateRender: true }, at);
    tl.fromTo(w, { y: 8, filter: "blur(5px)" }, { y: 0, filter: "blur(0px)", duration: 0.45, ease: "expo.out", immediateRender: true }, at);
  }
  function cutIn(tl, el, at) {
    tl.fromTo(el, { opacity: 0 }, { opacity: 1, duration: 2 / 30, ease: "none", immediateRender: true }, at);
  }
  function maskCss(el, v) {
    el.style.webkitMaskImage = v;
    el.style.maskImage = v;
  }

  // catalog vial (graded, alpha) with floor reflection; h = vial height px
  const VR = 606 / 1240;
  function vial(parent, name, x, y, h, withSheen) {
    const w = h * VR;
    const box = PP.el("div", "vial", parent, { style: `left:${x - w / 2}px;top:${y}px;width:${w}px;height:${h}px` });
    const src = "assets/plates/vials/" + name + ".png";
    PP.el("img", "refl", box, { src, alt: "" });
    PP.el("img", "", box, { src, alt: "" });
    let sheen = null;
    if (withSheen) {
      sheen = PP.el("div", "sheen", box);
      maskCss(sheen, `url(${src})`);
    }
    return { box, sheen, x: x - w / 2, w };
  }

  // ------------------------------------------------------------ shots
  function build(tl) {
    // 2 · 1.6–6.0  a single line of light draws the silhouette (rim_still), fade-in from black at 1.6
    {
      const s = $("s02");
      const wrap = PP.el("div", "layer", s);
      const base = plate(tl, wrap, P("rim_full"), 1.6, 6.0, { s: 1.0 }, { s: 1.0 + 0.008 * 4.4 });
      const lineWrap = PP.el("div", "layer", s, { style: "mix-blend-mode:screen" });
      const line = plate(tl, lineWrap, P("rim_full"), 1.6, 6.0, { s: 1.0 }, { s: 1.0 + 0.008 * 4.4 });
      line.style.filter = "brightness(2.4) contrast(1.2)";
      tl.fromTo(s, { opacity: 0 }, { opacity: 1, duration: 0.5, ease: "power1.in", immediateRender: true }, 1.6);
      PP.drive(tl, (t) => {
        const p = 12 + 21 * (t - 2.0); // front, % of frame height: 21 %/s (cap rim at 2.1 s -> base at ~5.9 s)
        const trail = t < 5.3 ? 0.34 : 0.34 + 0.36 * Math.min(1, (t - 5.3) / 0.7); // silhouette settles in behind the line
        maskCss(wrap, `linear-gradient(to bottom, rgba(0,0,0,${trail}) 0%, rgba(0,0,0,${trail}) ${p - 9}%, #000 ${p - 1}%, #000 ${p}%, rgba(0,0,0,0) ${p + 4}%)`);
        maskCss(lineWrap, `linear-gradient(to bottom, rgba(0,0,0,0) ${p - 3.5}%, #000 ${p - 0.6}%, #000 ${p}%, rgba(0,0,0,0) ${p + 1.8}%)`);
      }, 1.6, 6.0, 1.6, 4.4, "none");
    }
    // 3 · 6–8 macro crimp (machined aluminium), push 1 %/s
    plate(tl, $("s03"), P("macro_crimp"), 6, 8, ...push(1, 2, 1.0));
    // 4 · 8–10 the blue cap alone in the dark
    {
      const s = $("s04");
      const img = plate(tl, s, P("cap_full"), 8, 10, ...push(0.8, 2, 1.02));
      maskCss(img, "linear-gradient(to bottom, #000 0%, #000 50%, rgba(0,0,0,0.22) 62%, rgba(0,0,0,0.04) 74%, rgba(0,0,0,0) 86%)"); // top-lit: the crimp falls into the dark
    }
    // 5 · 10–12.5 REVEAL: whole vial, pool of light, push 0.8 %/s
    plate(tl, $("s05"), P("hero_full"), 10, 12.5, ...push(0.8, 2.5, 1.0));
    // 6 · 12.5–14.5 brand card
    {
      const s = $("s06");
      const g = PP.el("div", "layer", s);
      PP.el("img", "", g, { src: "assets/brand/brand-symbol-neon.svg", alt: "", style: `position:absolute;left:${960 - (100 * 405) / 456 / 2}px;top:${540 - 100 - 22}px;height:100px;width:${(100 * 405) / 456}px` });
      const wmW = 424;
      PP.el("img", "", g, { src: "assets/brand/brand-wordmark-light.svg", alt: "", style: `position:absolute;left:${960 - wmW / 2}px;top:${540 + 24}px;width:${wmW}px;height:${(wmW * 62) / 611}px` });
      tl.fromTo(g, { scale: 1 }, { scale: 1.016, duration: 2, ease: "none", immediateRender: true }, 12.5);
    }
    // 7 · 14.5–20 details / inserts
    plate(tl, $("s07a"), P("label_logo"), 14.5, 15.5, ...push(1.4, 1, 1.0));
    plate(tl, $("s07d"), P("cap_ribs"), 17.0, 17.4, ...push(1.5, 0.4, 1.0));
    {
      const s = $("s07f");
      plate(tl, s, P("label_word"), 17.9, 18.9, ...push(1.2, 1, 1.0));
      sweep(tl, s, 17.9, 18.9, -10, 40, 0.18); // soft specular sweep across the label
    }
    plate(tl, $("s07h"), P("macro_shoulder"), 19.4, 20.0, ...push(1.6, 0.6, 1.0));
    // 8 · 20–24 signature turntable: camera still, light fixed (video v08, untouched)
    // 9 · 24–27 vial in the left third + card built word by word
    plate(tl, $("s09"), P("hero_full"), 24, 27, { s: 1.0, x: -330 }, { s: 1.0 * 1.012, x: -334 });
    {
      const { ws } = words($("t09"), ["Every batch.", "Independently tested."], "left:1060px;top:476px");
      [24.15, 24.42, 24.75, 25.05].forEach((t, i) => wordIn(tl, ws[i], t));
    }
    // 10 · 27–33 four macros x 1.5 s, pull-out -2 %/s
    plate(tl, $("s10a"), P("label_full"), 27, 28.5, { s: 1.06 }, { s: 1.06 * (1 - 0.02 * 1.5) });
    plate(tl, $("s10b"), P("macro_full"), 28.5, 30, { s: 1.06 }, { s: 1.06 * (1 - 0.02 * 1.5) });
    plate(tl, $("s10c"), P("cap_full"), 30, 31.5, { s: 1.06, x: -300 }, { s: 1.06 * (1 - 0.02 * 1.5), x: -300 });
    plate(tl, $("s10d"), P("s3_macro"), 31.5, 33, { s: 1.06, x: -420 }, { s: 1.06 * (1 - 0.02 * 1.5), x: -420 });
    {
      const { ws } = words($("t10"), ["99% purity.", "Minimum."], "left:1250px;top:476px");
      [30.0, 30.25, 30.7].forEach((t, i) => wordIn(tl, ws[i], t));
    }
    // 11 · 33–36 cold light: backlit silhouette, frost-like haze
    {
      const s = $("s11");
      plate(tl, s, P("s3_cold"), 33, 36, { s: 1.0, x: 380 }, { s: 1.0 * 1.03, x: 386 });
      haze(tl, s, 33, 36, { op: 0.16, x0: 60, x1: -40, y0: 20, y1: -30, src: "smoke0", tint: "hue-rotate(0deg)", mask: "radial-gradient(ellipse 34% 58% at 70% 48%, #000 25%, rgba(0,0,0,0) 100%)" });
      const { ws } = words($("t11"), ["Shipped cold.", "Within 24 hours."], "left:300px;top:476px");
      [33.15, 33.42, 33.85, 34.1, 34.38].forEach((t, i) => wordIn(tl, ws[i], t));
    }
    // 12 · 36–38 burst: 8 x 250 ms, identical framing, only the product AND the world change (Apple colour-way cut)
    {
      const s = $("s12");
      const worlds = [BG.white, BG.blue, BG.black, BG.grey, BG.navy, BG.sky, BG.white, BG.blue];
      const order = ["selank-10", "ghk-cu-50", "cjc-1295-ipa-10", "semax-10", "igf-1-lr3-1", "bpc157-tb500-10", "ghk-cu-50", "selank-10"];
      const slots = order.map((n, i) => {
        const g = PP.el("div", "layer", s, { style: `background:${worlds[i].bg}` });
        PP.el("div", worlds[i].light ? "shadow" : "pool", g, { style: "left:610px;top:860px;width:700px;height:120px" });
        vial(g, n, 960, 120, 800);
        return g;
      });
      PP.drive(tl, (v) => {
        const k = Math.min(7, Math.floor(v + 1e-6));
        slots.forEach((el, i) => (el.style.opacity = i === k ? 1 : 0));
      }, 0, 8, 36, 2, "none");
    }
    // 13 · 38–39 match cut: the photoreal vial at the burst's exact size, held 1 s
    plate(tl, $("s13"), P("hero_full"), 38, 39, ...push(0.8, 1, 1.0));
    // 14 · 39–46 acceleration (beats 39 + 0.5k): speed ramps 8–15 %/s
    vmove(tl, "v14b", 40, 41, { s: 1.0 }, { s: 1.12 }, "power2.in");
    [39.0, 41.0].forEach((t, i) => flare(tl, t, [372, 610][i], i % 2 ? -1 : 1));
    {
      const { ws } = words($("t14"), ["Buy more. Save more."], "left:0;width:1920px;text-align:center;top:900px;font-size:60px;text-shadow:0 2px 24px rgba(0,0,0,0.85)");
      [39.2, 39.34, 39.48, 39.76].forEach((t, i) => wordIn(tl, ws[i], t));
    }
    // 18 · 42–44 PROMO white studio: two vials, « 2 vials · 5% off » on the VO words
    offer(tl, $("s18"), 42, 44, BG.white, ["bpc157-tb500-10", "ghk-cu-50"], "2 vials", "5% off", [42.15, 42.63], "#0b1f4d", "#1f4fd1");
    // 19 · 44–46 PROMO brand blue: three vials, « 3+ vials · 8% off »
    offer(tl, $("s19"), 44, 46, BG.blue, ["selank-10", "semax-10", "igf-1-lr3-1"], "3+ vials", "8% off", [44.15, 44.49], "#e8eefc", "#ffffff");
    // 15 · 46–50 line-up on glossy black, final light sweep ~20 %/s
    {
      const s = $("s15");
      s.style.background = BG.white.bg;
      const g = PP.el("div", "layer", s);
      PP.el("div", "shadow", g, { style: "left:120px;top:770px;width:1680px;height:130px" });
      const names = ["bpc157-tb500-10", "cjc-1295-ipa-10", "ghk-cu-50", "igf-1-lr3-1", "selank-10", "semax-10"];
      const h = 520, gap = 292;
      const vs = names.map((n, i) => vial(g, n, 960 + (i - 2.5) * gap, 290, h, true));
      tl.fromTo(g, { scale: 1.045 }, { scale: 1.045 * (1 - 0.01 * 4), duration: 4, ease: "none", immediateRender: true }, 46);
      PP.drive(tl, (x) => {
        vs.forEach((v) => {
          v.sheen.style.background = `linear-gradient(100deg, rgba(255,255,255,0) ${x - v.x - 170}px, rgba(255,255,255,0.5) ${x - v.x}px, rgba(255,255,255,0) ${x - v.x + 170}px)`;
        });
      }, 150, 150 + 0.2 * 1920 * 3.8, 46.1, 3.8, "none");
      const { ws } = words(s, ["Free shipping over $200."], "left:0;width:1920px;text-align:center;top:112px;font-size:60px;color:#0b1f4d");
      [46.3, 46.44, 47.36, 47.7].forEach((t, i) => wordIn(tl, ws[i], t));
      const sub = PP.el("div", "t", s, { text: "Discounts applied automatically in the cart.", style: "left:0;width:1920px;text-align:center;top:196px;font-size:30px;font-weight:500;color:#3f4a5a" });
      cutIn(tl, sub, 48.4);
    }
    // 16 · 50–53 single vial backlit in smoke
    {
      const s = $("s16");
      plate(tl, s, P("s3_back"), 50, 53, ...push(1.0, 3, 1.0));
      haze(tl, s, 50, 53, { op: 0.55, x0: -60, x1: 40, y0: 30, y1: -50, src: "smoke0", mask: "radial-gradient(ellipse 42% 62% at 50% 46%, #000 20%, rgba(0,0,0,0) 100%)" });
      haze(tl, s, 50, 53, { op: 0.4, x0: 80, x1: -30, y0: -10, y1: -60, src: "smoke1", s0: 1.25, s1: 1.3, mask: "radial-gradient(ellipse 50% 70% at 50% 50%, #000 15%, rgba(0,0,0,0) 100%)" });
    }
    // 17 · 53–60 logo (final hit 53.00), sweep 1.2 s, tagline 54.20, URL 55.00, legal from 53.40
    {
      const s = $("s17");
      s.style.background = BG.navy.bg;
      const symH = 140, symW = (symH * 405) / 456;
      const symTop = 318;
      const sym = PP.el("div", "", s, { style: `position:absolute;left:${960 - symW / 2}px;top:${symTop}px;width:${symW}px;height:${symH}px` });
      PP.el("img", "", sym, { src: "assets/brand/brand-symbol-neon.svg", alt: "", style: "width:100%;height:100%;display:block" });
      const wmW = 330, wmH = (wmW * 62) / 611;
      const wm = PP.el("div", "", s, { style: `position:absolute;left:${960 - wmW / 2}px;top:${symTop + symH + 30}px;width:${wmW}px;height:${wmH}px` });
      PP.el("img", "", wm, { src: "assets/brand/brand-wordmark-light.svg", alt: "", style: "width:100%;height:100%;display:block" });
      const sh1 = PP.el("div", "layer", sym, { style: "mix-blend-mode:screen" });
      const sh2 = PP.el("div", "layer", wm, { style: "mix-blend-mode:screen" });
      maskCss(sh1, "url(assets/brand/brand-symbol-neon.svg)");
      maskCss(sh2, "url(assets/brand/brand-wordmark-light.svg)");
      [sh1, sh2].forEach((e) => { e.style.webkitMaskSize = "100% 100%"; e.style.maskSize = "100% 100%"; });
      const symL = 960 - symW / 2, wmL = 960 - wmW / 2;
      PP.drive(tl, (x) => {
        const band = (l) => `linear-gradient(100deg, rgba(255,255,255,0) ${x - l - 120}px, rgba(255,255,255,0.85) ${x - l}px, rgba(255,255,255,0) ${x - l + 120}px)`;
        sh1.style.background = band(symL);
        sh2.style.background = band(wmL);
      }, 960 - 330, 960 + 330, 53.0, 1.2, "power1.inOut");
      const tag = PP.el("div", "t", s, { text: "Purity, proven.", style: "left:0;width:1920px;text-align:center;top:556px;font-size:40px" });
      const cta = PP.el("div", "cta", s, { text: "Shop now", style: "left:840px;top:640px;width:240px;height:68px" });
      const url = PP.el("div", "t soft", s, { text: "purepeptide.care", style: "left:0;width:1920px;text-align:center;top:736px;font-size:30px;font-weight:500;letter-spacing:0.01em;color:#c3cbd6" });
      const legal = PP.el("div", "t", s, { text: "For laboratory research use only · Not for human or veterinary consumption · 21+", style: "left:0;width:1920px;text-align:center;top:986px;font-size:24px;font-weight:500;color:#9aa3b0;letter-spacing:0.005em" });
      cutIn(tl, tag, 54.26);
      tl.fromTo(cta, { opacity: 0, scale: 0.94 }, { opacity: 1, scale: 1, duration: 0.35, ease: "expo.out", immediateRender: true }, 55.7);
      tl.fromTo(cta, { scale: 1 }, { scale: 0.96, duration: 0.08, ease: "power1.in", yoyo: true, repeat: 1, immediateRender: false }, 56.6); // the « click »
      cutIn(tl, url, 56.14);
      cutIn(tl, legal, 53.4);
    }
  }

  // worlds (backgrounds) for the promo / colour-way shots
  const BG = {
    white: { bg: "radial-gradient(ellipse 90% 70% at 50% 38%, #ffffff 0%, #f1f3f6 55%, #d9dee5 100%)", light: true },
    grey: { bg: "linear-gradient(180deg, #e9ecf0 0%, #e9ecf0 68%, #cfd5dd 100%)", light: true },
    blue: { bg: "radial-gradient(ellipse 80% 90% at 62% 42%, #2e66ea 0%, #163f9f 48%, #071a47 100%)", light: false },
    navy: { bg: "radial-gradient(ellipse 70% 80% at 50% 42%, #10285e 0%, #081536 55%, #02060f 100%)", light: false },
    sky: { bg: "linear-gradient(165deg, #9fd3ff 0%, #4d8ff0 55%, #1d4fc4 100%)", light: false },
    black: { bg: "#000", light: false },
  };
  // promo offer shot: world + vials on the right + two-line offer on the left (words land on the VO)
  function offer(tl, s, t0, t1, world, names, l1, l2, at, c1, c2) {
    s.style.background = world.bg;
    const g = PP.el("div", "layer", s);
    const h = 600, gap = 250, cx = 1320 - ((names.length - 1) * gap) / 2;
    PP.el("div", world.light ? "shadow" : "pool", g, { style: `left:${cx - 260}px;top:${250 + h - 60}px;width:${(names.length - 1) * gap + 520}px;height:120px` });
    names.forEach((n, i) => vial(g, n, cx + i * gap, 250, h));
    tl.fromTo(g, { scale: 1 }, { scale: 1.02, duration: t1 - t0, ease: "none", immediateRender: true }, t0);
    const a = PP.el("div", "t", s, { text: l1, style: `left:200px;top:372px;font-size:84px;color:${c1}` });
    const b = PP.el("div", "t", s, { text: l2, style: `left:192px;top:470px;font-size:168px;line-height:1;letter-spacing:-0.03em;color:${c2}` });
    wordIn(tl, a, at[0]);
    tl.fromTo(b, { opacity: 0, scale: 0.9 }, { opacity: 1, scale: 1, duration: 0.3, ease: "expo.out", immediateRender: true }, at[1]);
  }

  // soft specular band sweeping horizontally across a shot (x in % of width)
  function sweep(tl, shot, t0, t1, x0, x1, a) {
    const el = PP.el("div", "layer", shot, { style: "mix-blend-mode:screen" });
    PP.drive(tl, (x) => {
      el.style.background = `linear-gradient(104deg, rgba(255,255,255,0) ${x - 14}%, rgba(255,255,255,${a}) ${x}%, rgba(255,255,255,0) ${x + 14}%)`;
    }, x0, x1, t0, t1 - t0, "none");
  }
  function haze(tl, shot, t0, t1, o) {
    const wrap = PP.el("div", "layer", shot, { style: `opacity:${o.op}` });
    maskCss(wrap, o.mask);
    const img = PP.el("img", "smoke", wrap, { src: "assets/fx/" + o.src + ".png", alt: "" });
    tl.fromTo(img, { x: o.x0, y: o.y0, scale: o.s0 || 1.1 }, { x: o.x1, y: o.y1, scale: o.s1 || 1.14, duration: t1 - t0, ease: "none", immediateRender: true }, t0);
  }
  function flare(tl, at, y, dir) {
    const f = PP.el("div", "flare", $("fx"), { style: `top:${y}px;opacity:0` });
    PP.drive(tl, (u) => {
      const x = -700 + 1200 * (1 - (1 - u) * (1 - u)); // power2.out travel
      const op = u <= 0 || u >= 1 ? 0 : 0.55 * Math.min(1, u / 0.15) * Math.min(1, (1 - u) / 0.6);
      f.style.transform = `translateX(${x * dir}px)`;
      f.style.opacity = op;
    }, 0, 1, at, 0.34, "none");
  }

  // ------------------------------------------------------------ global: film grain (8 tiles, new offset every frame)
  function grain(tl) {
    const g = $("grain");
    const R = PP.rng(99);
    const offs = Array.from({ length: 1801 }, () => [Math.floor(R() * 512), Math.floor(R() * 512)]);
    PP.drive(tl, (v) => {
      const n = Math.max(0, Math.min(1800, Math.round(v)));
      g.style.backgroundImage = `url(assets/fx/grain${n % 8}.png)`;
      g.style.backgroundPosition = `${offs[n][0]}px ${offs[n][1]}px`;
    }, 0, 1800, 0, 60, "none");
  }

  FILM.build = function () {
    const tl = gsap.timeline({ paused: true });
    grain(tl);
    build(tl);
    return tl;
  };
})();
