// GENERATED by tools/build_vo.py — ElevenLabs v4 take (Markmont), word onsets on the video timeline (s).
window.VO = {
 "L01": {
  "at": 2.4,
  "end": 4.55,
  "text": "Most labels promise purity.",
  "words": [
   [
    2.4,
    "Most"
   ],
   [
    2.71,
    "labels"
   ],
   [
    3.01,
    "promise"
   ],
   [
    3.43,
    "purity."
   ]
  ]
 },
 "L02": {
  "at": 6.3,
  "end": 7.77,
  "text": "Few can prove it.",
  "words": [
   [
    6.3,
    "Few"
   ],
   [
    6.63,
    "can"
   ],
   [
    6.87,
    "prove"
   ],
   [
    7.23,
    "it."
   ]
  ]
 },
 "L03": {
  "at": 12.72,
  "end": 14.71,
  "text": "This is PurePeptide.",
  "words": [
   [
    12.72,
    "This"
   ],
   [
    12.91,
    "is"
   ],
   [
    13.19,
    "Pure"
   ],
   [
    13.75,
    "Peptide."
   ]
  ]
 },
 "L04": {
  "at": 20.3,
  "end": 23.56,
  "text": "Identity, confirmed. Purity, measured.",
  "words": [
   [
    20.3,
    "Identity"
   ],
   [
    20.81,
    "confirmed."
   ],
   [
    21.63,
    "Purity"
   ],
   [
    22.33,
    "measured."
   ]
  ]
 },
 "L05": {
  "at": 24.15,
  "end": 26.54,
  "text": "Every batch, independently tested.",
  "words": [
   [
    24.15,
    "Every"
   ],
   [
    24.34,
    "batch"
   ],
   [
    24.6,
    "independently"
   ],
   [
    25.3,
    "tested."
   ]
  ]
 },
 "L06": {
  "at": 30.0,
  "end": 32.97,
  "text": "Ninety-nine percent purity. Minimum.",
  "words": [
   [
    30.0,
    "99"
   ],
   [
    30.45,
    "%"
   ],
   [
    30.89,
    "purity."
   ],
   [
    31.71,
    "Minimum."
   ]
  ]
 },
 "L07": {
  "at": 33.25,
  "end": 35.75,
  "text": "Shipped cold, within twenty-four hours.",
  "words": [
   [
    33.25,
    "Shipped"
   ],
   [
    33.52,
    "cold"
   ],
   [
    33.78,
    "within"
   ],
   [
    34.3,
    "24"
   ],
   [
    34.82,
    "hours."
   ]
  ]
 },
 "L08": {
  "at": 36.1,
  "end": 38.48,
  "text": "Six compounds. One standard.",
  "words": [
   [
    36.1,
    "Six"
   ],
   [
    36.33,
    "compounds,"
   ],
   [
    37.03,
    "one"
   ],
   [
    37.57,
    "standard."
   ]
  ]
 },
 "L09": {
  "at": 39.2,
  "end": 41.01,
  "text": "Buy more, save more.",
  "words": [
   [
    39.2,
    "Buy"
   ],
   [
    39.41,
    "more,"
   ],
   [
    39.79,
    "save"
   ],
   [
    40.29,
    "more."
   ]
  ]
 },
 "L10": {
  "at": 42.05,
  "end": 44.09,
  "text": "Two vials, five percent off.",
  "words": [
   [
    42.05,
    "Two"
   ],
   [
    42.14,
    "vials,"
   ],
   [
    42.66,
    "5"
   ],
   [
    43.02,
    "%"
   ],
   [
    43.38,
    "off."
   ]
  ]
 },
 "L11": {
  "at": 44.13,
  "end": 46.14,
  "text": "Three or more, eight percent off.",
  "words": [
   [
    44.13,
    "Three"
   ],
   [
    44.3,
    "or"
   ],
   [
    44.42,
    "more,"
   ],
   [
    44.78,
    "8"
   ],
   [
    45.14,
    "%"
   ],
   [
    45.46,
    "off."
   ]
  ]
 },
 "L12": {
  "at": 46.3,
  "end": 49.0,
  "text": "Free shipping on orders over two hundred dollars.",
  "words": [
   [
    46.3,
    "Free"
   ],
   [
    46.47,
    "shipping"
   ],
   [
    46.81,
    "on"
   ],
   [
    47.01,
    "orders"
   ],
   [
    47.33,
    "over"
   ],
   [
    47.61,
    "$200."
   ]
  ]
 },
 "L13": {
  "at": 50.15,
  "end": 52.42,
  "text": "No promises. Just proof.",
  "words": [
   [
    50.15,
    "No"
   ],
   [
    50.24,
    "promises,"
   ],
   [
    50.76,
    "just"
   ],
   [
    51.48,
    "proof."
   ]
  ]
 },
 "L14": {
  "at": 53.3,
  "end": 56.02,
  "text": "PurePeptide. Purity, proven.",
  "words": [
   [
    53.3,
    "Pure"
   ],
   [
    53.51,
    "Peptide."
   ],
   [
    54.19,
    "Purity"
   ],
   [
    54.87,
    "Proven."
   ]
  ]
 },
 "L15": {
  "at": 56.1,
  "end": 58.72,
  "text": "Shop now, at purepeptide dot care.",
  "words": [
   [
    56.1,
    "Shop"
   ],
   [
    56.33,
    "now"
   ],
   [
    56.59,
    "at"
   ],
   [
    56.99,
    "purepeptide"
   ],
   [
    57.85,
    ".care."
   ]
  ]
 }
};
window.VO.w = (id, i) => window.VO[id].words[i][0];
