#!/usr/bin/env python3
"""Builds js/vo.js from the chosen ElevenLabs take (assets/audio/raw/vo_d.mp3, Hugo, eleven_v3).

Line cuts come from measured silences in the take; word onsets from Whisper large-v3
(tools/vo_words_whisper.json), pushed out of silences, then shifted onto the video timeline."""
import json, re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
words = json.load(open(ROOT / "tools/vo_words_whisper.json"))
SIL = [(1.36,1.73),(3.88,4.74),(7.88,8.30),(9.87,10.08),(10.22,10.36),(11.28,11.95),(12.98,13.15),(13.73,14.23),
       (16.62,16.85),(17.01,17.14),(17.61,18.17),(20.21,20.41),(21.28,21.99),(22.65,22.94),(23.55,23.94)]
# id, source cut [s0, s1] in the take, placement on the video timeline, display text
LINES = [
 ("L1", (0.00, 1.40), 0.30, "Vous achetez des peptides en ligne ?"),
 ("L2", (1.66, 3.94), 1.95, "Mais savez-vous vraiment ce qu’il y a dans la fiole ?"),
 ("L3", (4.66, 7.92), 4.50, "Chez PurePeptide, chaque lot part dans un laboratoire indépendant."),
 ("L4", (8.22, 11.34), 8.20, "On vérifie que c’est bien le bon produit, et on mesure sa pureté."),
 ("L5", (11.88, 13.80), 11.70, "99 %, minimum."),
 ("L6", (14.16, 17.66), 14.00, "Et le rapport d’analyse est publié en ligne. Vous pouvez tout vérifier."),
 ("L7", (18.10, 21.34), 17.95, "Six références, expédiées sous 24 heures, vers 10 pays."),
 ("L8", (21.92, 24.32), 22.30, "PurePeptide. La pureté, prouvée."),
]
# merge whisper sub-tokens: 'il, -vous, %, Peptide
toks = []
for t0, t1, w in words:
    if toks and (w in ("?", "!", ".", ",") or w.startswith("'") or w.startswith("-") or w in ("%", "%,") or (toks[-1][2] == "Pure" and w.startswith("Peptide"))):
        toks[-1] = [toks[-1][0], t1, toks[-1][2] + w]
    else:
        toks.append([t0, t1, w])
# energy onsets measured in the take (30 ms rise > 6 dB), used to snap Whisper's word starts
ONS = [float(x) for x in "0.07 0.24 0.43 0.54 0.66 0.82 0.94 1.72 1.92 2.04 2.15 2.51 2.99 3.08 3.20 3.30 3.41 3.59 3.66 4.74 4.99 5.19 5.31 5.37 5.43 5.53 5.67 5.81 5.95 6.01 6.25 6.38 6.45 7.07 7.38 7.53 7.65 8.29 8.71 8.87 9.01 9.14 9.38 9.57 10.07 10.35 10.88 10.97 11.17 11.94 12.07 12.14 12.21 12.64 12.83 13.14 14.48 14.61 14.80 15.18 15.29 15.54 16.16 16.38 16.51 16.84 17.14 17.45 17.51 18.15 18.25 18.30 18.40 18.53 18.62 18.95 19.06 19.17 19.50 19.59 19.77 19.89 19.97 20.41 20.50 20.64 20.92 21.98 22.20 22.33 22.38 22.45 22.55 22.93 23.14 23.38 23.93 24.04 24.17".split()]
def snap(t):
    c = min(ONS, key=lambda o: abs(o - t))
    return c if abs(c - t) <= 0.12 else t
def unsil(t):
    for a, b in SIL:
        if a - 0.08 <= t < b: return b
    return t
out = []
for lid, (s0, s1), at, text in LINES:
    lw = [w for w in toks if s0 - 0.05 <= unsil(w[0]) < s1]
    disp = []
    for d in text.split(" "):
        if disp and d in ("?", "!", ":", ";"): disp[-1] += " " + d
        else: disp.append(d)
    if lid == "L5": disp = ["99 %,", "minimum."]  # "99 %" spoken as one word
    assert len(lw) == len(disp), (lid, [w[2] for w in lw], disp)
    sh = at - s0
    ws = []
    for i, (w, d) in enumerate(zip(lw, disp)):
        t0 = max(snap(unsil(w[0])), s0, (ws[-1]["t0"] - sh + 0.07) if ws else 0)
        t1 = lw[i + 1][0] if i + 1 < len(lw) else min(w[1] + 0.25, s1)
        ws.append({"w": d, "t0": round(t0 + sh, 3), "t1": round(max(t1, t0 + 0.08) + sh, 3)})
    # speech end = last word end (clamped to cut)
    out.append({"id": lid, "src": [s0, s1], "at": at, "text": text, "words": ws, "end": round(min(s1, lw[-1][1] + 0.15) + sh, 3)})
js = "// Voice-over (Hugo, ElevenLabs eleven_v3, take « d »): line cut in the take, placement on the video timeline,\n// word onsets (Whisper large-v3, pushed out of measured silences). Generated by tools/build_vo.py — do not edit.\nwindow.PP = window.PP || {};\nPP.VO = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n"
(ROOT / "js/vo.js").write_text(js)
for l in out: print(l["id"], l["at"], "->", l["end"], " | ".join(f'{w["w"]}@{w["t0"]}' for w in l["words"]))
