// GENERATED by tools/build_vo.py — ElevenLabs v4 take (Markmont), word onsets on the video timeline (s).
window.VO = {
 "L01": {
  "at": 1.2,
  "end": 3.516,
  "text": "Anyone can print the word pure.",
  "words": [
   [
    1.2,
    "Anyone"
   ],
   [
    1.45,
    "can"
   ],
   [
    1.67,
    "print"
   ],
   [
    1.93,
    "the"
   ],
   [
    2.11,
    "word"
   ],
   [
    2.37,
    "pure."
   ]
  ]
 },
 "L02": {
  "at": 3.55,
  "end": 4.92,
  "text": "We'd rather spell it out.",
  "words": [
   [
    3.55,
    "We'd"
   ],
   [
    3.78,
    "rather"
   ],
   [
    4.0,
    "spell"
   ],
   [
    4.26,
    "it"
   ],
   [
    4.46,
    "out."
   ]
  ]
 },
 "L03": {
  "at": 5.4,
  "end": 6.66,
  "text": "Identity, confirmed.",
  "words": [
   [
    5.4,
    "Identity"
   ],
   [
    5.95,
    "confirmed."
   ]
  ]
 },
 "L04": {
  "at": 7.1,
  "end": 9.763,
  "text": "Purity, measured by HPLC.",
  "words": [
   [
    7.1,
    "Purity,"
   ],
   [
    7.49,
    "measured"
   ],
   [
    7.97,
    "by"
   ],
   [
    8.25,
    "HPLC."
   ]
  ]
 },
 "L05": {
  "at": 9.813,
  "end": 11.712,
  "text": "Ninety-nine percent. Minimum.",
  "words": [
   [
    9.813,
    "99"
   ],
   [
    10.243,
    "%"
   ],
   [
    10.583,
    "minimum."
   ]
  ]
 },
 "L06": {
  "at": 11.762,
  "end": 15.237,
  "text": "Every batch, independently tested. by Janoshik Analytical.",
  "words": [
   [
    11.762,
    "Every"
   ],
   [
    11.932,
    "batch"
   ],
   [
    12.172,
    "independently"
   ],
   [
    12.812,
    "tested."
   ],
   [
    13.597,
    "by"
   ],
   [
    13.907,
    "Janosik"
   ],
   [
    14.447,
    "Analytical."
   ]
  ]
 },
 "L07": {
  "at": 15.287,
  "end": 18.511,
  "text": "Shipped cold, within twenty-four hours. to ten countries.",
  "words": [
   [
    15.287,
    "Shipped"
   ],
   [
    15.537,
    "cold"
   ],
   [
    15.797,
    "within"
   ],
   [
    16.237,
    "24"
   ],
   [
    16.677,
    "hours."
   ],
   [
    17.457,
    "to"
   ],
   [
    17.527,
    "10"
   ],
   [
    17.727,
    "countries."
   ]
  ]
 },
 "L08": {
  "at": 18.561,
  "end": 20.781,
  "text": "Six compounds. One standard.",
  "words": [
   [
    18.561,
    "Six"
   ],
   [
    18.791,
    "compounds,"
   ],
   [
    19.491,
    "one"
   ],
   [
    19.971,
    "standard."
   ]
  ]
 },
 "L09": {
  "at": 20.831,
  "end": 21.981,
  "text": "Don't take our word for it.",
  "words": [
   [
    20.831,
    "Don't"
   ],
   [
    21.001,
    "take"
   ],
   [
    21.101,
    "our"
   ],
   [
    21.281,
    "word"
   ],
   [
    21.461,
    "for"
   ],
   [
    21.661,
    "it."
   ]
  ]
 },
 "L10": {
  "at": 22.7,
  "end": 23.551,
  "text": "See for yourself.",
  "words": [
   [
    22.7,
    "See"
   ],
   [
    22.87,
    "for"
   ],
   [
    22.97,
    "yourself."
   ]
  ]
 },
 "L11": {
  "at": 26.05,
  "end": 27.95,
  "text": "Now, let the cart do the math.",
  "words": [
   [
    26.05,
    "Now,"
   ],
   [
    26.32,
    "let"
   ],
   [
    26.68,
    "the"
   ],
   [
    26.86,
    "cart"
   ],
   [
    27.14,
    "do"
   ],
   [
    27.32,
    "the"
   ],
   [
    27.44,
    "math."
   ]
  ]
 },
 "L12": {
  "at": 28.3,
  "end": 30.04,
  "text": "Two vials? Five percent off.",
  "words": [
   [
    28.3,
    "Two"
   ],
   [
    28.39,
    "vials,"
   ],
   [
    28.79,
    "5"
   ],
   [
    29.19,
    "%"
   ],
   [
    29.47,
    "off."
   ]
  ]
 },
 "L13": {
  "at": 30.15,
  "end": 31.72,
  "text": "Three or more? Eight percent.",
  "words": [
   [
    30.15,
    "Three"
   ],
   [
    30.32,
    "or"
   ],
   [
    30.42,
    "more,"
   ],
   [
    30.7,
    "8%."
   ]
  ]
 },
 "L14": {
  "at": 31.77,
  "end": 33.84,
  "text": "Over two hundred dollars? Free shipping.",
  "words": [
   [
    31.77,
    "Over"
   ],
   [
    31.92,
    "$200,"
   ],
   [
    32.66,
    "free"
   ],
   [
    33.16,
    "shipping."
   ]
  ]
 },
 "L15": {
  "at": 33.95,
  "end": 36.01,
  "text": "Applied automatically, right in the cart.",
  "words": [
   [
    33.95,
    "Applied"
   ],
   [
    34.24,
    "automatically,"
   ],
   [
    34.92,
    "right"
   ],
   [
    35.32,
    "in"
   ],
   [
    35.48,
    "the"
   ],
   [
    35.54,
    "cart."
   ]
  ]
 },
 "L16": {
  "at": 37.55,
  "end": 39.87,
  "text": "PurePeptide. Purity, proven.",
  "words": [
   [
    37.55,
    "Pure"
   ],
   [
    37.74,
    "Peptide."
   ],
   [
    38.38,
    "Purity"
   ],
   [
    38.94,
    "proven."
   ]
  ]
 },
 "L17": {
  "at": 41.7,
  "end": 43.98,
  "text": "Shop now at purepeptide dot care.",
  "words": [
   [
    41.7,
    "Shop"
   ],
   [
    41.91,
    "now"
   ],
   [
    42.13,
    "at"
   ],
   [
    42.45,
    "purepeptide"
   ],
   [
    43.21,
    ".care."
   ]
  ]
 }
};
window.VO.w = (id, i) => window.VO[id].words[i][0];
