// S01 · hook · "Anyone can print the word… pure." · window f0–f105 (0.000–3.500 s) · INK · SVG + DOM (SCENES §S01).
// Markup (outline paths, clean-word placement) is generated by tools/s01_build.py from hero.mp4 @0.50 s at canvas scale 0.957.
// main.js shows/hides the section; every tween here is at absolute seconds.
PP.scene("S01", function build(tl, root) {
  const F = (n) => n / 30;
  // Frame-0 workaround (local, main.js untouched): main.js adds tl.set(root,{opacity:0},0) AND tl.set(root,{opacity:1},IN=0).
  // When the runtime seeks back to t=0 the two zero-duration sets at 0 are reverted in reverse order and S01 ends hidden on
  // f0 (proven in a scratch build). Drop the redundant opacity:0 set for this scene only; the OUT set at f105 stays.
  tl.getTweensOf(root).filter((t) => t.startTime() === 0 && t.vars.opacity === 0).forEach((t) => t.kill());
  gsap.set(root, { opacity: 1 });
  const box = root.querySelector(".s01-stamps");
  const cx = +box.dataset.cx, cy = +box.dataset.cy; // label_c (stage px)

  // ------------------------------------------------------------------ outline: 35 % → 100 % over f0–f30 (HIT1), power2.out
  // Two half paths (base centre → flank → cap-top centre). A bright 3 % draw-head rides each tip and fades after they meet.
  const svg = root.querySelector(".s01-vial");
  const halves = [...svg.querySelectorAll(".s01-ol")].map((p) => {
    const L = p.getTotalLength();
    const tip = PP.svg("path", { d: p.getAttribute("d"), class: "s01-tip" }, svg);
    return { p, tip, L };
  });
  const SEG = 0.03;
  const setDraw = (v) => {
    for (const h of halves) {
      const a = v * h.L;
      h.p.style.strokeDasharray = `${a.toFixed(2)} ${(h.L + 2).toFixed(2)}`;
      const s = Math.min(a, SEG * h.L);
      h.tip.style.strokeDasharray = `${s.toFixed(2)} ${(h.L + 2).toFixed(2)}`;
      h.tip.style.strokeDashoffset = (-(a - s)).toFixed(2);
    }
  };
  const t1 = CUES.HIT1; // f30
  PP.drive(tl, setDraw, 0.35, 1, 0, t1, "power2.out");
  // draw-heads: full at f0, meet at the cap top on HIT1, then fade (6 f power2.out); the outline keeps its 2 px #93A1B8
  const tips = halves.map((h) => h.tip);
  tl.set(tips, { opacity: 0.9 }, 0);
  tl.fromTo(tips, { opacity: 0.9 }, { opacity: 0, duration: F(6), ease: "power2.out", immediateRender: false }, t1);

  // ------------------------------------------------------------------ cheap stamps
  // Land frames (BRIEF SFX #1). Fonts cycle Anton → Archivo 900 → Plex Mono 500 → Inter Tight 300 → Archivo 800.
  const LAND = [0, 12, 22, 30, 37, 43, 48, 52, 55];
  const STYLE = [
    { f: "f-anton", t: "PURE", px: 132 },
    { f: "f-arch9", t: "PURE", px: 62, b: "b-box", ls: 0.08 },
    { f: "f-plex", t: "pure", px: 100 },
    { f: "f-tight", t: "pure", px: 124 },
    { f: "f-arch8", t: "Pure", px: 86, b: "b-pill" },
    { f: "f-anton", t: "pure", px: 128, b: "b-rule" },
    { f: "f-arch9", t: "PURE", px: 58, b: "b-dbl", ls: 0.1 },
    { f: "f-plex", t: "PURE", px: 98 },
    { f: "f-tight", t: "pure", px: 128 },
  ];
  const rnd = PP.rng(11);
  // clean "pure" lands on VO "pure" (L01 word 5), clamped to f70–f88, snapped to the frame grid
  const tClean = Math.round(PP.clamp(VO.w("L01", 5), F(70), F(88), "S01 clean pure") * 30) / 30;
  const stamps = STYLE.map((s, i) => {
    const el = PP.el("div", `s01-st ${s.f}`, box);
    const inner = (c) => PP.el("span", `${c} ${s.b || ""}`, el, { text: s.t });
    inner("g");
    inner("i");
    el.style.fontSize = s.px + "px";
    if (s.ls) el.style.letterSpacing = s.ls + "em";
    // seeded crookedness: rotation ±1–4°, a few px of misplacement, a different patch of the worn rubber
    const sign = rnd() < 0.5 ? -1 : 1;
    const rot = sign * (1 + 3 * rnd());
    const dx = (rnd() - 0.5) * 16, dy = (rnd() - 0.5) * 12;
    el.style.webkitMaskPosition = el.style.maskPosition = `${-Math.round(rnd() * 380)}px ${-Math.round(rnd() * 160)}px`;
    // centre the element's box on label_c (percent-based: independent of font metrics or load timing)
    el.style.left = cx + "px";
    el.style.top = cy + "px";
    gsap.set(el, { xPercent: -50, yPercent: -50, x: dx, y: dy, rotation: rot, scale: 1, transformOrigin: "50% 50%" });
    return el;
  });
  stamps.forEach((el, i) => {
    const t = F(LAND[i]);
    const tOff = i < stamps.length - 1 ? F(LAND[i + 1]) : tClean; // hard cut to the next stamp; the last one holds (the stall)
    tl.set(el, { opacity: 1 }, t);
    if (i === 0) {
      // already mid-stamp at f0: scale 1.03 (≈ 0.7 f into the 3 f power4.out land), settling over the remaining 2.3 f
      tl.fromTo(el, { scale: 1.03 }, { scale: 1, duration: F(2.3), ease: "power3.out", immediateRender: true }, 0);
    } else {
      tl.fromTo(el, { scale: 1.12 }, { scale: 1, duration: F(3), ease: "power4.out", immediateRender: false }, t);
    }
    tl.set(el, { opacity: 0 }, tOff);
  });

  // ------------------------------------------------------------------ the clean word
  // DM Sans 800 150 px #F3F6FA, perfectly registered on label_c; scale 1.04 → 1 over 4 f expo.out; holds to f105.
  const pure = root.querySelector(".s01-pure");
  tl.set(pure, { opacity: 1 }, tClean);
  tl.fromTo(pure, { scale: 1.04, svgOrigin: `${cx} ${cy}` }, { scale: 1, svgOrigin: `${cx} ${cy}`, duration: F(4), ease: "expo.out", immediateRender: false }, tClean);

  // ------------------------------------------------------------------ polish: the clean stamp rings through the glass
  // On the clean-word frame, four short light pulses leave the outline at label height (both flanks) and run up and
  // down the glass, converging on the cap-top and base centres 18 f later while they fade (position power3.out, alpha
  // power2.in). It is the only move during the hold, it rhymes with the f0–f30 draw-heads and with the D6 glass tink
  // (SFX #3), and it is fully gone by f90 so the f104 OUT state (= typevial.mp4 frame 0) is untouched.
  const RING = 18; // frames
  const ringPaths = halves.map((h) => {
    // arc length where this half crosses label_c y on its flank (path runs base centre → flank → cap-top centre)
    let s0 = 0;
    for (let s = 0; s <= h.L; s += 2) if (h.p.getPointAtLength(s).y <= cy) { s0 = s; break; }
    const up = PP.svg("path", { d: h.p.getAttribute("d"), class: "s01-ring" }, svg);
    const dn = PP.svg("path", { d: h.p.getAttribute("d"), class: "s01-ring" }, svg);
    return { L: h.L, s0, up, dn };
  });
  const seg = (el, L, a, b, alpha) => {
    a = Math.max(0, a); b = Math.min(L, b);
    if (alpha <= 0.002 || b - a < 0.5) { el.style.opacity = 0; return; }
    el.style.opacity = alpha.toFixed(3);
    el.style.strokeDasharray = `${(b - a).toFixed(2)} ${(L + 4).toFixed(2)}`;
    el.style.strokeDashoffset = (-a).toFixed(2);
  };
  const ringOut = gsap.parseEase("power3.out"), ringFade = gsap.parseEase("power2.in");
  PP.driveT(tl, (t) => {
    const p = (t - tClean) / F(RING);
    const on = p >= 0 && p < 1;
    for (const r of ringPaths) {
      if (!on) { r.up.style.opacity = 0; r.dn.style.opacity = 0; continue; }
      const k = ringOut(p), alpha = 0.95 * (1 - ringFade(p)), half = 34 * (1 - 0.6 * k);
      const su = r.s0 + (r.L - r.s0) * k, sd = r.s0 * (1 - k);
      seg(r.up, r.L, su - half, su + half, alpha);
      seg(r.dn, r.L, sd - half, sd + half, alpha);
    }
  }, tClean - F(0.5), tClean + F(RING + 1));
});
