#!/usr/bin/env python3
"""Generates the app localisation files from the translation source apps/i18n/strings/*.json.

  scripts/gen-i18n.py            write Swift .lproj/Localizable.strings and the TS dictionary
  scripts/gen-i18n.py --check    list interface strings used in code that have no translation

Each file maps English keys to {"fr": ..., "es": ..., "zh-Hans": ...}; files are merged. Keys come from the
Swift `tr("...")` calls (placeholders `%@`) and the React `t("...")` calls (placeholders `{name}`).
A missing translation falls back to English at runtime, so the file may lag behind the code.
"""
import json, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / "apps/i18n/strings"
LANGS = ["fr", "es", "zh-Hans"]
SWIFT_DIR = ROOT / "apps/macos/Sources/DevDoctor"
TS_DIR = ROOT / "apps/desktop/src"

def swift_literal(src, i):
    """Returns (end, text) for the Swift string literal starting at src[i] == '"' (no interpolation)."""
    j = i + 1; out = []
    while j < len(src):
        c = src[j]
        if c == "\\":
            nxt = src[j + 1]
            out.append({"n": "\n", "t": "\t", '"': '"', "\\": "\\", "'": "'"}.get(nxt, "\\" + nxt)); j += 2; continue
        if c == '"':
            return j + 1, "".join(out)
        out.append(c); j += 1
    raise ValueError("unterminated")

def swift_keys():
    keys = set()
    for f in SWIFT_DIR.glob("*.swift"):
        src = f.read_text()
        for m in re.finditer(r'\btr\(\s*"', src):
            _, text = swift_literal(src, m.end() - 1)
            keys.add(text)
    return keys

def ts_keys():
    keys = set()
    for f in list(TS_DIR.rglob("*.tsx")) + list(TS_DIR.rglob("*.ts")):
        if f.name.startswith("i18n"):
            continue
        src = f.read_text()
        for m in re.finditer(r'\bt\(\s*"((?:[^"\\]|\\.)*)"', src):
            keys.add(json.loads('"' + m.group(1) + '"'))
    return keys

def strings_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

def main():
    data = {}
    for f in sorted(SOURCE_DIR.glob("*.json")):
        part = json.loads(f.read_text())
        dup = set(part) & set(data)
        if dup:
            print(f"duplicate keys in {f.name}: {sorted(dup)[:5]}", file=sys.stderr)
        data.update(part)
    if "--check" in sys.argv:
        used = swift_keys() | ts_keys()
        missing = sorted(k for k in used if k not in data)
        unused = sorted(k for k in data if k not in used)
        for k in missing:
            print("MISSING", json.dumps(k, ensure_ascii=False))
        print(f"{len(used)} keys used, {len(missing)} without translation, {len(unused)} unused entries", file=sys.stderr)
        return
    for lang in LANGS:
        lproj = SWIFT_DIR / "Resources" / f"{lang}.lproj"
        lproj.mkdir(parents=True, exist_ok=True)
        lines = [f"/* Generated by scripts/gen-i18n.py from apps/i18n/strings/*.json ({lang}). Do not edit. */", ""]
        for key in sorted(data):
            value = data[key].get(lang)
            if value and value != key:
                lines.append(f'"{strings_escape(key)}" = "{strings_escape(value)}";')
        (lproj / "Localizable.strings").write_text("\n".join(lines) + "\n")
    table = {lang: {k: v[lang] for k, v in sorted(data.items()) if v.get(lang) and v[lang] != k} for lang in LANGS}
    ts = "// Generated by scripts/gen-i18n.py from apps/i18n/strings/*.json. Do not edit by hand.\n"
    ts += "export const TRANSLATIONS: Record<string, Record<string, string>> = " + json.dumps(table, ensure_ascii=False, indent=2) + ";\n"
    (TS_DIR / "lib/i18n.generated.ts").write_text(ts)
    print(f"{len(data)} keys → {', '.join(f'{lang}: {len(table[lang])}' for lang in LANGS)}")

if __name__ == "__main__":
    main()
