export const meta = {
  name: 'pp-motion-pro-concept',
  description: 'Research 3D product motion-design craft + feasibility tests (Blender CPU, screen-in-3D), 3 competing 3D-first concepts judged, synthesized into BRIEF.md + SHOTS.md for a pro motion-design film with the photoreal iPhone as hero',
  phases: [
    { title: 'Research', detail: '3D motion craft from pro studios; Blender/compositing feasibility tests; sound' },
    { title: 'Concepts', detail: '3 independent 3D-first concepts (shot lists)' },
    { title: 'Judge', detail: '3 judges score every concept' },
    { title: 'Bible', detail: 'BRIEF.md + SHOTS.md' },
  ],
}

const ROOT = '/home/user/DevDoctor/ads'
const OUT = ROOT + '/purepeptide-motion-pro-en'
const V1 = ROOT + '/purepeptide-motion-en'
const RULES = `
CLIENT FEEDBACK ON THE PREVIOUS FILM (${V1}, "Spelled out", see its BRIEF.md/SCENES.md and renders/draft_contact.png): "really good, but it is more of an AD. I want a real MOTION DESIGN piece worthy of a pro motion designer. I loved the very realistic 3D phone." So: NO offer cards, NO stamped "APPLIED AUTOMATICALLY", NO kinetic-type sales pitch, no ad grammar. Think Behance/Vimeo-staff-pick 3D product motion: physically based CGI, camera language, materials (glass, brushed metal, frost, liquid, light), seamless object-led transitions, UI that lives in 3D space (screen elements extruding from the phone into depth), bold but sparse typography, sound design locked to picture. The photoreal iPhone (Blender model, Deep Blue, no Apple logo) is the HERO object and must carry the piece; the real purepeptide.care site lives on its screen (real captures, assets/site/clean). The real vial appears via the existing photoreal AI clips (assets/plates/ai: turn, hero, cold, smoke, cap, macro) or the catalog PNGs with alpha (assets/vials) — never a CG vial with a fake label.
HARD RULES (compliance, binding): English, research positioning. Legal line on the end card >= 2.5 s, >= 24 px: "For laboratory research use only · Not for human or veterinary consumption · 21+". NEVER show or mention people, hands, fingers, faces, body parts, syringes, needles, pills, injections, doctors, dosages, protocols, effects or benefits (no health, recovery, muscle, weight, anti-aging, results, benefits, heal, treatment, dose, cycle). No invented numbers, certifications, reviews, awards, competitor names. Only these claims: every batch independently tested (Janoshik Analytical, text only); identity confirmed; HPLC purity 99 % minimum; shipped cold within 24 h; ships to 10 countries (no names); six compounds (names only as printed on labels); offers may be GLIMPSED on the real cart screen (volume discount −5 %/−8 % on the same compound, free shipping over $200) but are not the subject; tagline "Purity, proven."; URL purepeptide.care. Never say certificates are published online. Retatrutide / MT-2 / shop grid / "Recovery" / "tissue repair" / BAC water / COA / G Pay never visible (the clean captures already hide them; see ${V1}/assets/site/SITE.md and assets/site/clean/meta.json). Text >= 24 px, contrast >= 4.5:1, title-safe x 96–1824 / y 54–1026.
VOICE (already recorded, do not rewrite): one ElevenLabs v4 performance, ~70 words, sparse and emotional. The exact text: "Pure. It's such an easy word to print... and such a hard one to prove. So we don't print it. We measure it. Every batch... every single one... tested independently. By Janoshik Analytical. Ninety-nine percent. Minimum. Shipped cold... within twenty-four hours. Don't take our word for it. Open the site. Let the cart do the math — it's automatic. PurePeptide. Purity... proven. purepeptide.care". Word timings will be in ${OUT}/js/vo.js (window.VO, VO.w(lineId, i)) — read it if it exists; else plan on ~40 s of speech spread over 45 s with pauses.
BUDGET/TOOLS: Blender 5 (Cycles CPU only — EEVEE is unavailable, no GPU; 4 CPUs; measured ~7 s/frame at 1080p for the phone alone at 12–24 samples + OIDN denoise; ONE Blender process at a time), HyperFrames (HTML/GSAP compositing, VP9-alpha video plates proven), Python (numpy/PIL, ffmpeg), the existing iPhone model ${OUT}/assets/iphone (PHONE.md, iphone.blend, tools/build_iphone.py, render_iphone.py: the screen is an emission texture that can be any PNG — and can be an image SEQUENCE so the real site scrolls/taps INSIDE true 3D shots). Total Blender render budget: <= 5 hours of CPU (e.g. ~900 frames at 20 s/frame or ~1300 at 12 s/frame). No new ElevenLabs video/music generations unless the sound agent proves one music track is essential (then exactly one, estimated first). No AI video generation.
Deliverable: 45.0 s, 1920x1080, 30 fps, 16:9 (a 9:16 reframe is NOT required).`

phase('Research')
const research = await parallel([
  () => agent(`You are a researcher on 3D product motion design. Use WebSearch/WebFetch widely (>= 15 sources): Behance and Vimeo staff picks of "iPhone app 3D motion", "product motion design", Apple product films (iPhone 15/16/17 launch films, "Apple Vision Pro" film, Apple Watch), ManvsMachine, Tendril, Ordinary Folk, BUCK, Aixsponza, Niceshit, Ouchhh, the "UI in 3D space" trend (screens extruding into layered cards, floating UI, parallax depth), CGI phone renders tutorials (Blender/C4D: lighting an iPhone, HDRI vs area lights, edge highlights, DOF, motion blur, macro lens look), transitions in 3D product films (match cut on object, camera push-through, light-leak, morph, object-led reveal, frost/liquid reveals), typography in 3D films (sparse, large, tracked, depth-sorted with objects), colour/grade (black studio vs white infinite vs tinted), rhythm (shot lengths, hold frames, speed ramps), sound design for CGI product films. Extract CONCRETE rules a Blender + HTML compositor can apply: camera focal lengths and moves (mm, speeds, eases), light rigs (sizes, positions, ratios), material values (roughness, anisotropy, IOR), DOF f-stops, motion blur shutter, how to stage UI cards in 3D (spacing, thickness, shadows), shot duration stats, transition recipes. Return a dense markdown craft bible (<= 1800 words) with numbered rules, 12 signature techniques (each with a Blender/compositing recipe), and a "what makes it look pro vs amateur CGI" checklist.`, { label: 'research:craft3d', phase: 'Research' }),
  () => agent(`You are the technical director. Establish FACTS by running tests (do not guess), on a 4-CPU machine shared with other agents — keep each Blender test under ~3 minutes, one Blender at a time. Blender venv: /home/user/DevDoctor/ads/purepeptide-blender/.venv/bin/python (bpy, Blender 5.0.1). Read ${OUT}/assets/iphone/PHONE.md and tools/build_iphone.py + render_iphone.py (the phone model: materials, studio, camera, shots API), ${V1}/BUILD.md and js/phone.js (the 2D rig), ${V1}/SCENES.md §0 (HyperFrames setup) and ${V1}/assets/site/SITE.md.
Tests to run and report with numbers: (1) Cycles s/frame at 1920x1080 for: phone alone (baseline), phone + 3 glass spheres + a glossy floor plane with DOF, phone + volumetric fog box, and the same at 1280x720 — each at 16 samples + OIDN and at 48 samples; (2) does an image SEQUENCE texture on the screen work (bpy: image.source='SEQUENCE', frame offsets) so that a scrolling site can be rendered inside a 3D shot — prove with 3 frames; (3) can UI "cards" be made as thin extruded planes with the clean capture crops as textures (do a 1-frame test with 3 cards floating in front of the phone screen, soft shadows, DOF) — show the PNG; (4) render-layer / pass outputs that help compositing: separate alpha, cryptomatte or object-index for the phone vs cards, Z-depth for 2D fog/DOF, and whether RGBA + a separate "screen-only" matte can be rendered so HyperFrames can overlay crisp HTML onto the 3D screen area even when the phone is slightly tilted (project the 4 screen corners per frame to JSON via world_to_camera_view, then CSS matrix3d / perspective-transform the HTML screen onto them — prove on 1 tilted frame by compositing in PIL with a homography); (5) ffmpeg: ProRes 4444 alpha + VP9 alpha encode from PNG sequences, and whether HyperFrames handles 2 overlapping alpha videos (quick 1 s render test in a scratch project). Write every script under ${OUT}/tools/tests/ and a markdown report ${OUT}/TECH.md with the numbers, the recommended pipeline (which shots in true 3D, which with the 2D rig, how the screen is composited), and a per-second render budget. Return the report.`, { label: 'research:tech', phase: 'Research' }),
  () => agent(`You are a sound designer and composer for CGI product films. (a) Research (WebSearch) how top 3D product films (Apple, ManvsMachine, Tendril) design sound: music structure for a 45 s piece (tempo, texture, when the drop lands, silence), sub hits on object landings, risers into reveals, "whoosh with tail" on camera moves, glass/metal foley for a phone and a vial, UI ticks, sonic logo. (b) Inventory what exists: ${V1}/assets/audio (mix.wav, music_raw.mp3, the SFX synthesized by tools/mix_audio.py + audiolib.py — read those two scripts and list every synth function), ${ROOT}/*/assets/audio/music_raw.mp3 (ffprobe durations; a 0.5 s RMS curve each with numpy) and say which track can carry a MOTION DESIGN piece (cinematic, modern, not "ad jingle"). (c) Decide: reuse an existing track (with the exact edit plan) OR generate ONE track with ElevenLabs eleven_music_v2_5 — if so, load the ElevenLabs MCP tools (ToolSearch select:mcp__ElevenLabs__creative_get_model_guide, creative_generate_in_flow or the music tool) and get the model guide + a credit ESTIMATE ONLY (estimate_only:true) for a 46 s instrumental; do NOT generate. Write the prompt you would use. Return markdown: music decision with evidence (and the estimate), a SFX vocabulary list mapped to synth recipes (existing functions or new ones to write), mixing targets (-14 LUFS, -1.5 dBTP, VO ducking), and a "sound hits must land on these picture events" template for the shot list.`, { label: 'research:sound', phase: 'Research' }),
])
const [craft, tech, sound] = research
const R = `## CRAFT (3D product motion)\n${craft}\n\n## TECH FACTS + PIPELINE\n${tech}\n\n## SOUND\n${sound}`
log('research done: ' + research.map(x => (x || '').length).join(', ') + ' chars')

phase('Concepts')
const ANGLES = [
  ['A', 'STUDIO — an Apple-grade black-and-white infinite studio: the phone and the vial are sculptural objects under moving softboxes; macro lenses, slow dollies, light sweeps along the aluminium edge, the camera pushes INTO the screen where the real site is live, UI elements step out of the glass as thin 3D cards; proof claims appear as single large words placed in the scene with correct depth/occlusion.'],
  ['B', 'MATERIAL — proof as physical material: frost crystallising over glass (cold chain), a droplet of light (purity), brushed metal (precision), the phone revealed from inside a block of clear ice/frost that shatters or melts; everything photoreal, slow and heavy, with sub-bass hits; the site on the screen is the warm moment at the end.'],
  ['C', 'DEPTH — a continuous one-take camera journey through layered space: an infinite light-grey lab grid with floating 3D planes (the six real vial images, the chromatogram-free "99 %" numeral as a solid object, the cart as extruded cards), parallax and DOF rack-focus, speed ramps, until the camera arrives at the phone standing on a surface and dives into its screen; typography is architectural and lives in Z.'],
]
const concepts = await parallel(ANGLES.map(([id, angle]) => () => agent(`You are a senior 3D motion designer / director at a top studio. Write concept ${id} for a 45.0 s PurePeptide motion-design film.
ANGLE: ${angle}
${RULES}
Research + tech facts:\n${R}\n
Deliver markdown: 1) title + one-line idea + why a motion-design jury would love it; 2) look (lighting rig, palette, lens set, materials, grade) for 4 key frames; 3) the VO placement (which words land on which shot — do not rewrite the VO); 4) a SHOT LIST of 8–14 shots with frame ranges at 30 fps, camera (focal, move, ease), what moves, materials, how the REAL site appears on the screen (which clean capture, scroll/tap events, 2D rig or in-3D image sequence), the transition into the next shot (object-led), the on-screen text (sparse), and the sound hits; 5) which shots are pure Blender renders (estimate frames × s/frame from TECH.md and keep the total <= 5 CPU hours), which are HyperFrames 2D rig, which are AI vial clips; 6) risks + fallbacks. Be specific enough that each shot can be built by a separate agent.`, { label: 'concept:' + id, phase: 'Concepts' })))

phase('Judge')
const JUDGES = [
  ['craft', 'a jury member of the Motion Awards / a creative director at ManvsMachine. Score: is this real motion design (not an ad)? visual ambition, originality, camera and material craft, transition craft, how the hero phone is used, typographic restraint, rhythm.'],
  ['client', 'the client: founder of PurePeptide who said the last film felt like an ad and loved the realistic 3D phone. Score how much each concept gives them the "pro motion designer" feeling, how prominent and beautiful the phone is, whether the site still reads clearly on screen, and whether the piece still communicates purity/proof and ends on the site.'],
  ['tech', 'the technical director who must deliver it in Blender Cycles CPU (4 cores, <= 5 CPU hours of rendering, one process) + HyperFrames, with parallel agents. Score feasibility at photoreal quality, risk, compliance with the HARD RULES (any violation = 0), and give a render-hour estimate per concept.'],
]
const scoreSchema = { type: 'object', properties: { scores: { type: 'array', items: { type: 'object', properties: { concept: { type: 'string' }, score: { type: 'number' }, strengths: { type: 'string' }, weaknesses: { type: 'string' }, steal: { type: 'string' } }, required: ['concept', 'score', 'strengths', 'weaknesses', 'steal'] } }, verdict: { type: 'string' } }, required: ['scores', 'verdict'] }
const C = concepts.map((c, i) => `=== CONCEPT ${ANGLES[i][0]} ===\n${c}`).join('\n\n')
const verdicts = await parallel(JUDGES.map(([k, who]) => () => agent(`You are ${who}\n${RULES}\nTECH FACTS:\n${tech}\nScore each concept 0–10 (decimals ok), with strengths, weaknesses and the single best idea to steal.\n\n${C}`, { label: 'judge:' + k, phase: 'Judge', schema: scoreSchema })))
const tally = {}
verdicts.filter(Boolean).forEach(v => v.scores.forEach(s => { const key = s.concept.replace(/[^ABC]/g, '').slice(0, 1) || s.concept; tally[key] = (tally[key] || 0) + s.score }))
log('tally ' + JSON.stringify(tally))

phase('Bible')
const bible = await agent(`You are the director. Synthesize the production bible for the PurePeptide 45 s motion-design film from the concepts and verdicts below. Start from the top concept (tally ${JSON.stringify(tally)}), graft the best steals, fix every weakness. ${RULES}
If ${OUT}/js/vo.js exists, read it and use the REAL word times (VO.w) for every voice-locked event; if ${OUT}/assets/audio/vo_v4/VOICE.md exists read it too.
Write:
1) ${OUT}/BRIEF.md — idea, look (lighting rig with exact light sizes/positions/energies for Blender, lens set, materials with values, palette hex, grade), typography (fonts in ${OUT}/assets/fonts), the VO placement table (word → frame), music plan (per the sound research; if one ElevenLabs music generation is recommended, give the exact prompt and the estimate), SFX list with frames, compliance checklist, render budget table (shot → frames × s/frame).
2) ${OUT}/SHOTS.md — the build contract for parallel builders: global setup (project layout: blender/<shot>.py builds+renders each shot from ${OUT}/assets/iphone/iphone.blend via a shared blender/common.py (phone import, studio, camera helpers, screen texture/sequence, pass outputs, per-frame screen-corner JSON), a single render queue tools/render_queue.py that renders shots sequentially at a chosen pct/samples and encodes PNG→VP9-alpha/ProRes; HyperFrames composition index.html with stage videos + a 2D phone rig reused from ${V1}/js/phone.js + per-shot overlays js/shots/<id>.js; audio via tools/mix_audio.py), then each shot: id, frames [in,out], type (3D / 2D rig / AI clip / hybrid), camera, motion, materials, the site state on screen (capture name, scroll, taps with frames, from clean/meta.json coordinates), how the screen is composited (baked in 3D vs HTML projected on the per-frame corners), the transition contract with neighbours (last/first frame match), text, sound hits, render settings (pct, samples, motion blur, DOF) and estimated render time. Also a QC checklist per shot.
Return a 15-line summary of the concept and shot list.

CONCEPTS:\n${C}\n\nVERDICTS:\n${JSON.stringify(verdicts, null, 1)}\n\nRESEARCH:\n${R}`, { label: 'bible', phase: 'Bible' })
return { tally, bible }
