#!/usr/bin/env python3
"""js/vo.js for the English film: one Kokoro (af_heart) file per line in assets/audio/vo/, speech bounds + word
onsets from assets/audio/vo/vo_words.json (energy gate + Whisper large-v3). `at` = video time where speech starts."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
W = json.load(open(ROOT / "assets/audio/vo/vo_words.json"))
PLACE = [  # id, video time of first phoneme, display text
 ("L01", 2.60, "Anyone can print 99% on a label."),
 ("L02", 5.80, "Anyone can say “lab tested.”"),
 ("L03", 8.40, "Almost no one shows you the proof."),
 ("L04", 12.30, "We do."),
 ("L05", 17.30, "Every batch, sent to an independent lab."),
 ("L06", 20.00, "Identity, confirmed."),
 ("L07", 22.00, "Purity, measured."),
 ("L08", 23.50, "99%. Minimum."),
 ("L09", 26.00, "Shipped cold, within 24 hours."),
 ("L10", 28.80, "Don’t take our word for it."),
 ("L11", 30.60, "Check it yourself."),
 ("L12", 36.20, "Pick your compound."),
 ("L13", 39.20, "See the purity. Verified."),
 ("L14", 42.00, "Order."),
 ("L15", 42.80, "Two vials, 5% off. Three or more, 8%."),
 ("L16", 49.50, "No promises. Just proof."),
 ("L18", 52.40, "PurePeptide."),
 ("L19", 53.60, "Purity, proven."),
]
out = []
for lid, at, text in PLACE:
    w = W[lid]
    s0, s1 = w["s0"], w["s1"]
    disp = text.split(" ")
    ws = w["words"]
    toks = []
    for t0, t1, x in ws:  # merge "99" "%" etc.
        if toks and x in ("%", "%,", "%."):
            toks[-1][1] = t1; toks[-1][2] += x
        else:
            toks.append([t0, t1, x])
    words = []
    if len(toks) == len(disp):
        for i, (t0, t1, _) in enumerate(toks):
            words.append({"w": disp[i], "t0": round(at + max(t0, s0) - s0, 3), "t1": round(at + t1 - s0, 3)})
    else:  # fall back to even spread
        n = len(disp)
        for i, d in enumerate(disp):
            words.append({"w": d, "t0": round(at + (s1 - s0) * i / n, 3), "t1": round(at + (s1 - s0) * (i + 1) / n, 3)})
        print("  (even spread)", lid, [t[2] for t in toks], disp)
    out.append({"id": lid, "file": f"assets/audio/vo/{lid}.wav", "src": [s0, s1], "at": at, "text": text, "words": words, "end": round(at + s1 - s0, 3)})
for a, b in zip(out, out[1:]):
    assert b["at"] >= a["end"], (a["id"], a["end"], b["id"], b["at"])
(ROOT / "js/vo.js").write_text("// Voice-over (English, Kokoro-82M « af_heart », one file per line): placement + word onsets. Generated by tools/build_vo.py.\nwindow.PP = window.PP || {};\nPP.VO = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n")
for l in out: print(l["id"], l["at"], "->", l["end"], " | ".join(f'{x["w"]}@{x["t0"]}' for x in l["words"]))
