// Voice-over (Hugo, ElevenLabs eleven_v3, take « d »): line cut in the take, placement on the video timeline,
// word onsets (Whisper large-v3, pushed out of measured silences). Generated by tools/build_vo.py — do not edit.
window.PP = window.PP || {};
PP.VO = [
 {
  "id": "L1",
  "src": [
   0.0,
   1.4
  ],
  "at": 0.3,
  "text": "Vous achetez des peptides en ligne ?",
  "words": [
   {
    "w": "Vous",
    "t0": 0.37,
    "t1": 0.45
   },
   {
    "w": "achetez",
    "t0": 0.44,
    "t1": 0.76
   },
   {
    "w": "des",
    "t0": 0.73,
    "t1": 0.84
   },
   {
    "w": "peptides",
    "t0": 0.84,
    "t1": 1.18
   },
   {
    "w": "en",
    "t0": 1.24,
    "t1": 1.32
   },
   {
    "w": "ligne ?",
    "t0": 1.31,
    "t1": 1.7
   }
  ],
  "end": 1.7
 },
 {
  "id": "L2",
  "src": [
   1.66,
   3.94
  ],
  "at": 1.95,
  "text": "Mais savez-vous vraiment ce qu’il y a dans la fiole ?",
  "words": [
   {
    "w": "Mais",
    "t0": 2.01,
    "t1": 2.09
   },
   {
    "w": "savez-vous",
    "t0": 2.08,
    "t1": 2.59
   },
   {
    "w": "vraiment",
    "t0": 2.59,
    "t1": 2.99
   },
   {
    "w": "ce",
    "t0": 2.99,
    "t1": 3.31
   },
   {
    "w": "qu’il",
    "t0": 3.28,
    "t1": 3.53
   },
   {
    "w": "y",
    "t0": 3.49,
    "t1": 3.57
   },
   {
    "w": "a",
    "t0": 3.59,
    "t1": 3.67
   },
   {
    "w": "dans",
    "t0": 3.66,
    "t1": 3.74
   },
   {
    "w": "la",
    "t0": 3.73,
    "t1": 3.81
   },
   {
    "w": "fiole ?",
    "t0": 3.8,
    "t1": 4.23
   }
  ],
  "end": 4.23
 },
 {
  "id": "L3",
  "src": [
   4.66,
   7.92
  ],
  "at": 4.5,
  "text": "Chez PurePeptide, chaque lot part dans un laboratoire indépendant.",
  "words": [
   {
    "w": "Chez",
    "t0": 4.58,
    "t1": 4.76
   },
   {
    "w": "PurePeptide,",
    "t0": 4.83,
    "t1": 5.4
   },
   {
    "w": "chaque",
    "t0": 5.37,
    "t1": 5.68
   },
   {
    "w": "lot",
    "t0": 5.65,
    "t1": 5.92
   },
   {
    "w": "part",
    "t0": 5.85,
    "t1": 6.1
   },
   {
    "w": "dans",
    "t0": 6.09,
    "t1": 6.28
   },
   {
    "w": "un",
    "t0": 6.29,
    "t1": 6.42
   },
   {
    "w": "laboratoire",
    "t0": 6.42,
    "t1": 6.98
   },
   {
    "w": "indépendant.",
    "t0": 6.91,
    "t1": 7.76
   }
  ],
  "end": 7.76
 },
 {
  "id": "L4",
  "src": [
   8.22,
   11.34
  ],
  "at": 8.2,
  "text": "On vérifie que c’est bien le bon produit, et on mesure sa pureté.",
  "words": [
   {
    "w": "On",
    "t0": 8.27,
    "t1": 8.35
   },
   {
    "w": "vérifie",
    "t0": 8.34,
    "t1": 8.66
   },
   {
    "w": "que",
    "t0": 8.69,
    "t1": 8.82
   },
   {
    "w": "c’est",
    "t0": 8.85,
    "t1": 9.0
   },
   {
    "w": "bien",
    "t0": 8.99,
    "t1": 9.12
   },
   {
    "w": "le",
    "t0": 9.12,
    "t1": 9.2
   },
   {
    "w": "bon",
    "t0": 9.19,
    "t1": 9.36
   },
   {
    "w": "produit,",
    "t0": 9.36,
    "t1": 9.66
   },
   {
    "w": "et",
    "t0": 9.55,
    "t1": 10.04
   },
   {
    "w": "on",
    "t0": 10.05,
    "t1": 10.32
   },
   {
    "w": "mesure",
    "t0": 10.33,
    "t1": 10.64
   },
   {
    "w": "sa",
    "t0": 10.64,
    "t1": 10.82
   },
   {
    "w": "pureté.",
    "t0": 10.86,
    "t1": 11.32
   }
  ],
  "end": 11.32
 },
 {
  "id": "L5",
  "src": [
   11.88,
   13.8
  ],
  "at": 11.7,
  "text": "99 %, minimum.",
  "words": [
   {
    "w": "99 %,",
    "t0": 11.76,
    "t1": 12.48
   },
   {
    "w": "minimum.",
    "t0": 12.46,
    "t1": 13.41
   }
  ],
  "end": 13.31
 },
 {
  "id": "L6",
  "src": [
   14.16,
   17.66
  ],
  "at": 14.0,
  "text": "Et le rapport d’analyse est publié en ligne. Vous pouvez tout vérifier.",
  "words": [
   {
    "w": "Et",
    "t0": 14.07,
    "t1": 14.15
   },
   {
    "w": "le",
    "t0": 14.14,
    "t1": 14.22
   },
   {
    "w": "rapport",
    "t0": 14.21,
    "t1": 14.42
   },
   {
    "w": "d’analyse",
    "t0": 14.45,
    "t1": 14.96
   },
   {
    "w": "est",
    "t0": 15.02,
    "t1": 15.1
   },
   {
    "w": "publié",
    "t0": 15.09,
    "t1": 15.4
   },
   {
    "w": "en",
    "t0": 15.38,
    "t1": 15.5
   },
   {
    "w": "ligne.",
    "t0": 15.5,
    "t1": 15.78
   },
   {
    "w": "Vous",
    "t0": 15.78,
    "t1": 16.06
   },
   {
    "w": "pouvez",
    "t0": 16.0,
    "t1": 16.32
   },
   {
    "w": "tout",
    "t0": 16.35,
    "t1": 16.7
   },
   {
    "w": "vérifier.",
    "t0": 16.68,
    "t1": 17.5
   }
  ],
  "end": 17.47
 },
 {
  "id": "L7",
  "src": [
   18.1,
   21.34
  ],
  "at": 17.95,
  "text": "Six références, expédiées sous 24 heures, vers 10 pays.",
  "words": [
   {
    "w": "Six",
    "t0": 18.0,
    "t1": 18.08
   },
   {
    "w": "références,",
    "t0": 18.1,
    "t1": 18.59
   },
   {
    "w": "expédiées",
    "t0": 18.47,
    "t1": 19.19
   },
   {
    "w": "sous",
    "t0": 19.19,
    "t1": 19.31
   },
   {
    "w": "24",
    "t0": 19.35,
    "t1": 19.57
   },
   {
    "w": "heures,",
    "t0": 19.62,
    "t1": 20.01
   },
   {
    "w": "vers",
    "t0": 20.26,
    "t1": 20.34
   },
   {
    "w": "10",
    "t0": 20.35,
    "t1": 20.63
   },
   {
    "w": "pays.",
    "t0": 20.63,
    "t1": 21.1
   }
  ],
  "end": 21.0
 },
 {
  "id": "L8",
  "src": [
   21.92,
   24.32
  ],
  "at": 22.3,
  "text": "PurePeptide. La pureté, prouvée.",
  "words": [
   {
    "w": "PurePeptide.",
    "t0": 22.36,
    "t1": 22.96
   },
   {
    "w": "La",
    "t0": 23.31,
    "t1": 23.39
   },
   {
    "w": "pureté,",
    "t0": 23.38,
    "t1": 23.88
   },
   {
    "w": "prouvée.",
    "t0": 24.31,
    "t1": 24.7
   }
  ],
  "end": 24.7
 }
];
